### ISSUE TITLE
java.lang.RuntimeException error after yarn run rename

### ISSUE THREAD

**Issue by viniciusdba27** [thecodingmachine/react-native-boilerplate#104]
Hello,

I just followed the steps and after running "yarn run rename lindacare" the App stops after launch.

Steps:
clone
yarn
yarn run rename -- <YourProjectName>
create your configuration file App/Config/index.js from index.dev.js (if you are in dev environment) and fill the missing values
yarn start
yarn android

error:
java.lang.RuntimeException: Unable to instantiate application com.lindacare.MainApplication: java.lang.ClassNotFoundException: Didn't find class "com.lindacare.MainApplication" on path: DexPathList[[zip file "/data/app/com.lindacare-Mg2OnoNU1ElOlKk-M-vlzg==/base.apk"],nativeLibraryDirectories=[/data/app/com.lindacare-Mg2OnoNU1ElOlKk-M-vlzg==/lib/x86, /data/app/com.lindacare-Mg2OnoNU1ElOlKk-M-vlzg==/base.apk!/lib/x86, /system/lib]]

can someone help me?

**Comment by JeremyDolle** [comment]
Hello @viniciusdba27,

the dependency used for renaming the app have some trouble for Windows users. Please look at this issue : #84. So check if `android/app/src/main/java/com/{your-package-name}/MainActivity.java` and `android/app/src/main/java/com/{your-package-name}/MainApplication.java` are still there. If not copy and paste them from the repo.

**Comment by AurelGit** [comment]
Rename is now not useful on the new implementation of the boilerplate !

You can directly use : 
```
npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
```
