### ISSUE TITLE
App crashes on storing data more than 6mb

### ISSUE THREAD

**Issue by farrukhalikhan** [thecodingmachine/react-native-boilerplate#107]
**Problem**
Since this project is using redux-persist/lib/storage it's limited to 6MB only. I am facing problem storing data more than 6 MB. when app grows bigger. I am always frustrated when the app crashes due to storage limit exceeded (Screenshot attached)

**Additional/Suggestion**
Is there any option to select any other package.
Anybody else resolved this issue on their end?
![Screenshot_20200711-181231_BAO](https://user-images.githubusercontent.com/67103874/87224937-a6df6d00-c3a2-11ea-83ad-44dcc3d05d15.jpg)

**Comment by rizwanatta** [comment]
this seems to be an issue with redux persist older version before 6.0! as I am using one which has more than 80mb and growing I have no issue with redux persist 6.0.0

maybe as if now it comes not with prebuild asyncStorage with redux! 
SOURCE:  https://github.com/rt2zz/redux-persist/releases

**Comment by AurelGit** [comment]
Thanks a lot @rizwanatta 

We are now using `redux-persist 6.0.0` :tada: 😃
