### ISSUE TITLE
Signing for "BoilerplateTests" requires a development team. Select a development team in the Signing & Capabilities editor.

### ISSUE THREAD

**Issue by anandchakru** [thecodingmachine/react-native-boilerplate#113]
**Describe the bug**
After I added development team, am still getting the following issue:
```
Signing for "BoilerplateTests" requires a development team. Select a development team in the Signing & Capabilities editor.
```

**To Reproduce**
git clone https://github.com/thecodingmachine/react-native-boilerplate.git
cd react-native-boilerplate
rm -rf .git
yarn install && cd ios && pod install
open Boilerplate.xcworkspace
Select BoilerPlate -> Signing & Capabilities -> Team -> Select team
Product menu -> Build

**Expected behavior**
Build should happen clean

**Screenshots**
<img width="960" alt="Screen Shot 2020-09-09 at 1 46 00 PM" src="https://user-images.githubusercontent.com/3580498/92653445-35894100-f2a3-11ea-83e0-4102df7cd6b1.png">

--
<img width="1081" alt="Screen Shot 2020-09-09 at 1 49 31 PM" src="https://user-images.githubusercontent.com/3580498/92653519-5487d300-f2a3-11ea-92ac-30672349a698.png">

**Smartphone (please complete the following information):**
 - iPhone 7
 - iOS13.7

**Additional context**
none

**Comment by JeremyDolle** [comment]
Sorry for the delay... Have you find the solution ?

**Comment by anandchakru** [comment]
> Sorry for the delay... Have you find the solution ?

No, started from scratch without this template and moved on

**Comment by JeremyDolle** [comment]
Ok, I think the problem comes from updates of react native in our template. Don't hesitate to try again, we've made the V2 from scratch to have a clean project, it is up to date with all dependencies, it is more easier to use and we are more reactive to answer the issues. 
Have a Nice day !
