### ISSUE TITLE
Redirect if not logged in

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#116]
How can we make authorization?
And if user is not logged in, redirect to loginscreen?

How can it be merged with boilerplate?

**Comment by JeremyDolle** [comment]
Hi, we have made a repository with a login by session exemple [here](https://github.com/thecodingmachine/react-native-workshop). This Will be refactored when the boilerplate V2 will be released but you have an exemple that can be used.
