### ISSUE TITLE
Error: spawn @thecodingmachine/react-native-boilerplate/post-init.script.js EACCES

### ISSUE THREAD

**Issue by AurelGit** [thecodingmachine/react-native-boilerplate#117]
When installing the new boilerplate, the post-init script failed with 

```
Error: spawn xxx/@thecodingmachine/react-native-boilerplate/post-init.script.js EACCES
```

Seems to be a permission issue, but it's not a "real" problem because nothing append in the post-init script 😃

**Comment by sirproton** [comment]
Had the same issue too

**Comment by JeremyDolle** [comment]
@sirproton you can use it even if you have the error because the post init script does nothing. We are working on it to avoid the error 😉

**Comment by AurelGit** [comment]
#121

**Comment by Sumit-Budhiraja** [comment]
Anyone still facing this issue.?
