### ISSUE TITLE
Error: Unable to resolve module `../Config` from `src/Services/index.js`

### ISSUE THREAD

**Issue by head-shot** [thecodingmachine/react-native-boilerplate#119]
When Running the App on a device, The following error pops up: 
![Simulator Screen Shot - iPhone 11 - 2020-10-23 at 15 38 41](https://user-images.githubusercontent.com/49337526/96994229-d8d9a100-1545-11eb-9e1a-2d23a2340b1b.png)

Works fine if I change the line: 
**import** { Config } from '@/Config'
to
**import { Config } from '@/Config/index.dev.js'**
or **index.staging.js** or **index.production.js**

Kindly look into resolving the issue as soon as possible!

**Comment by JeremyDolle** [comment]
Hello, please read this section : https://thecodingmachine.github.io/react-native-boilerplate/docs/Installation#running-the-project. You have to copy and rename the right config !
