### ISSUE TITLE
ERROR: This module isn't specified in a package.json.

### ISSUE THREAD

**Issue by urchihe** [thecodingmachine/react-native-boilerplate#120]
yarn remove v1.21.1
[1/2] 🗑  Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:20212) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/apple/Documents/Projects/Personal/NewCode/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'
    at Object.lstatSync (fs.js:845:3)
    at walk (/Users/apple/Documents/Projects/Personal/NewCode/node_modules/@react-native-community/cli/build/tools/walk.js:38:22)
    at copyProjectTemplateAndReplace (/Users/apple/Documents/Projects/Personal/NewCode/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (/Users/apple/Documents/Projects/Personal/NewCode/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:20212) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20212) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JeremyDolle** [comment]
Please check the solution [here](https://github.com/thecodingmachine/react-native-boilerplate/issues/118)

**Comment by JeremyDolle** [comment]
If you have resolve the issue please give me your previous node version

**Comment by urchihe** [comment]
It did not work here, I had node 12.13.1 and  npm 6.12.1 before and upgraded it to node 15.0.1 and npm 7.0.5  and still the same error, tried on both mac and windows.

**Comment by JeremyDolle** [comment]
Can you try to run ´npm uninstall -g react-native-cli´ and ´yarn global add @react-native-community/cli´

**Comment by urchihe** [comment]
I have this issue in mac ⠼ Downloading template
⠼ Downloading template
✔ Downloading template
✔ Copying template
✔ Processing template
✖ Executing post init script 
error Error: spawn /var/folders/zx/4l7fdx893yzbyrq6wr7dsqrc0000gn/T/rncli-init-template-KAxotB/node_modules/@thecodingmachine/react-native-boilerplate/post-init.script.js EACCES

**Comment by urchihe** [comment]
Installed very well in windows.

**Comment by JeremyDolle** [comment]
Yes we are working on the post init script error. You have a related issue about it. But you can use the boilerplate even if you have the error because the post init script do nothing! So enjoy !

**Comment by andreymaslovru** [comment]
Try to do
- `yarn global list`
after that, you will get a list of dependencies where you have react-native and react-native-cli installed
next 
- `yarn global remove <dependencies>`

its all, run your command

**Comment by fidenz-sanka** [comment]
> Can you try to run `npm uninstall -g react-native-cli` and `yarn global add @react-native-community/cli`

I got the same error when I try to run `yarn global remove create-react-app`
I ran `yarn global add create-react-app`, then I could create a react app
