### ISSUE TITLE
AddToCart Action

### ISSUE THREAD

**Issue by Cortlandd** [thecodingmachine/react-native-boilerplate#123]
Say I wanted to make an add to cart action and I simple wanted it to persist locally as opposed to a server call?

Below is my thinking...except the confusion comes with handling the productId being passed and updating `addedCartItems: []` which would be part of the module state. Should I pass the productId along with the state as the parameters instead of only the productId? Or should it be in Services because it can apply to more than just api clients?

```js
import { buildAction, buildReducers } from '@/Store/builder'

export default {
    initialState:  { loading: false, error: null },
    action: buildAction('user/addToCart', (productId) => {
        
    }),
    reducers: buildReducers({ itemKey: null }),
}
```

**Comment by JeremyDolle** [comment]
Hello @Cortlandd I don't really understand your question.
If you want to persist your state, you have to add the slice name into the `whiteList` property of the `persistConfig` located at `src/Store/index.js`.

For the second paragraph of your issue, I am not sure to understand your question. Do you want to add the `productId` to `addedCartItems` and not using API call for this action ?

**Comment by Cortlandd** [comment]
> For the second paragraph of your issue, I am not sure to understand your question. Do you want to add the productId to addedCartItems and not using API call for this action ?

Yes.

**Comment by JeremyDolle** [comment]
Ok I understand, the documentation of `buildAction`, `buildSlice` and `buildReducers` will arrives very soon to help. But these functions helps you with common CRUP operation for now (it will be updated soon to be more powerful).So, If you want an action that mutate a state you simply have to do something like this :

A cart slice :
```
const initialState = [AddToCart].reduce(
  (acc, module) => ({
    ...acc,
    ...module.initialState,
  }),
  {/*initial state*/},
)

const slice = createSlice({
  'cart',
  initialState,
  extraReducers: (builder) => {
    builder.addCase(AddToCart.action, AddToCart.reducers)
  },
})

````

A addToCart feature
```
export default {
  initialState: {
    addedItems: [],
  },
  action: createAction('cart/addToCart'),
  reducers: {
    addToCart: (state, { payload }) => {
      state.addedItems = [
        ...state.addedItems,
        payload,
      ]
    }
  }
}
``` 

For the moment, the builder cannot help you, so you have to use redux-toolkit itself. But thanks for your question it gives us a lot of ideas to make a better builder !

**Comment by Cortlandd** [comment]
Thanks. This helps!

**Comment by Cortlandd** [comment]
Question. How would I pass a parameter to the above? Sign as a `productId`

**Comment by JeremyDolle** [comment]
A parametre to an action or a reducer ?

**Comment by Cortlandd** [comment]
> A parametre to an action or a reducer ?

The action. If i pass in a `productId` to AddToCart, that productId would be in addedItems or added somewhere else.

**Comment by JeremyDolle** [comment]
Can you give me your actual code please ? (the action and the related reducer)

**Comment by Cortlandd** [comment]
I was going off of the example you made above that used redux directly.

**Comment by JeremyDolle** [comment]
Ok, so you have to dispatch the action like this : 
```
...
import AddToCart from '@/Store/Cart/AddToCart'
...
const MyContainer = () => {
   const dispatch = useDispatch()
   ...
   const fetch = (productId) => {
      dispatch(AddToCart.action(productId))
  }
   ...
   return(
     <>
        <TextInput
          onChangeText={(productId) => fetch(productId)}
        />
     </>
 )
}
```

If you link correctly the action to the associate reducer, you will see in the reducer 2 parameters : 
 - The state,
 - The action (=> {type:'cart/addToCart', payload } where payload is equal to the productId)

**Comment by Cortlandd** [comment]
Okay thats exactly what I thought. 

**Question:** If I'd like to give general feedback or inform you on something I discovered while using the boilerplate, should I just make an issue?

**Comment by JeremyDolle** [comment]
Yes thank you, we will tag your issue with the `Question` label or `Feedback` 😉
