### ISSUE TITLE
react-native init doesnt work

### ISSUE THREAD

**Issue by Rimondlu** [thecodingmachine/react-native-boilerplate#125]
**Describe the bug**
Unable to initialise 
`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`
doesnt work

**To Reproduce**
`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

**Screenshots**
![image](https://user-images.githubusercontent.com/32009768/97907922-1934ec80-1d9a-11eb-9173-a3b75f6cbcfe.png)

**Other infos**
The entire folder might have to be renamed to `react-native-template-boilerplate`
I m not too sure either

**Comment by JeremyDolle** [comment]
Hi, What is your version of @react-native-community/cli ?

**Comment by Rimondlu** [comment]
Sorry for the trouble, apparently there is an issue with my node. reinstall node seem to fix the issue.
