### ISSUE TITLE
this boilerplate is lacking a default .gitignore file.

### ISSUE THREAD

**Issue by xyz0405** [thecodingmachine/react-native-boilerplate#126]
I use this template a lot. But every time I create a new app. I manually add a .gitignore file.

**Comment by JeremyDolle** [comment]
Thanks for the issue, we are working on it 👍

**Comment by aminhdev** [comment]
https://github.com/thecodingmachine/react-native-boilerplate/releases/tag/v3.6.2
This problem issued in this version again
