### ISSUE TITLE
Jest test suilts are failed to run

### ISSUE THREAD

**Issue by vinayakb-pits** [thecodingmachine/react-native-boilerplate#129]
I created an example app using this template and the app runs really well on the device. however I try to run the test, Then I got the following  error 

`yarn test
yarn run v1.22.5
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    E:\DSPC\node_modules\@thecodingmachine\redux-toolkit-wrapper\src\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './wrappers'
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

    > 1 | import { buildSlice } from '@thecodingmachine/redux-toolkit-wrapper'
        | ^
      2 | import InitStartup from './Init'
      3 | 
      4 | export default buildSlice('startup', [InitStartup]).reducer

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/Store/Startup/index.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.944 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Environment

System:
    OS: Windows 10 10.0.15063
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 5.08 GB / 15.91 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 4.6.1 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by JeremyDolle** [comment]
Hi @vinayakb-pits, thanks for the report we will check that and come with answers

**Comment by JeremyDolle** [comment]
We found the reason why it is not working. We are on it ;)
