### ISSUE TITLE
npx react-native init doesn't work

### ISSUE THREAD

**Issue by showstop** [thecodingmachine/react-native-boilerplate#130]
Hello. 
I try make a new project with this boilerplate. but I can't do it 
could you help me?

![image](https://user-images.githubusercontent.com/20079122/98760989-cd2c1c80-2417-11eb-9238-eac408212742.png)

**Comment by showstop** [comment]
it is cause of legacy version of react-native-cli

after installing a new version of cli, this issue is resovled.

**Comment by kvlknctk** [comment]
I have some issue, I was tried uninstall and install react-native-cli. 
```bash
```

**Comment by kvlknctk** [comment]
Okay, Resolved. 
```bash
npm uninstall -g react-native-cli
yarn global add @react-native-community/cli
```
