### ISSUE TITLE
Problem installation template

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#132]
Hi @AurelGit , @JeremyDolle : 

I created a new project with the following command:

`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

Then I went through all the next steps, but what I find inside the app is this, not the template.

What am I doing wrong?

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  ScrollView,
  View,
  Text,
  StatusBar,
} from 'react-native';

import {
  Header,
  LearnMoreLinks,
  Colors,
  DebugInstructions,
  ReloadInstructions,
} from 'react-native/Libraries/NewAppScreen';

const App: () => React$Node = () => {
  return (
    <>
      <StatusBar barStyle="dark-content" />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>
          <Header />
          {global.HermesInternal == null ? null : (
            <View style={styles.engine}>
              <Text style={styles.footer}>Engine: Hermes</Text>
            </View>
          )}
          <View style={styles.body}>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Step One</Text>
              <Text style={styles.sectionDescription}>
                Edit <Text style={styles.highlight}>App.js</Text> to change this
                screen and then come back to see your edits.
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>See Your Changes</Text>
              <Text style={styles.sectionDescription}>
                <ReloadInstructions />
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Debug</Text>
              <Text style={styles.sectionDescription}>
                <DebugInstructions />
              </Text>
            </View>
            <View style={styles.sectionContainer}>
              <Text style={styles.sectionTitle}>Learn More</Text>
              <Text style={styles.sectionDescription}>
                Read the docs to discover what to do next:
              </Text>
            </View>
            <LearnMoreLinks />
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
};

const styles = StyleSheet.create({
  scrollView: {
    backgroundColor: Colors.lighter,
  },
  engine: {
    position: 'absolute',
    right: 0,
  },
  body: {
    backgroundColor: Colors.white,
  },
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: Colors.black,
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
    color: Colors.dark,
  },
  highlight: {
    fontWeight: '700',
  },
  footer: {
    color: Colors.dark,
    fontSize: 12,
    fontWeight: '600',
    padding: 4,
    paddingRight: 12,
    textAlign: 'right',
  },
});

export default App;
```

**Comment by JeremyDolle** [comment]
Hi, are you sure about the command you enter ? Because it seems that the --template doesn't work.

**Comment by Angelk90** [comment]
@JeremyDolle : I made copy and paste.

**Comment by JeremyDolle** [comment]
I don't understand How you have this devDependencies. 

If you want to use this boilerplate you have to create a New project by running : `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`. This command will create a New project called `MyApp` using the react-native-cli. You can not using it in an existing project. 

If you doing it right, can you give me your environment.

**Comment by Angelk90** [comment]
@JeremyDolle : In fact, I create a new project, it is created and those are the dependencies that I find inside the package.json file, to make you understand.

I noticed now that at the moment of creation the following warm is given:

```
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:5367) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/name/Desktop/MyApp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'
    at Object.lstatSync (fs.js:1007:3)
    at walk (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/tools/walk.js:38:22)
    at copyProjectTemplateAndReplace (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createProjectFromTemplate (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:118:3)
    at async Object.initCompat (/Users/name/Desktop/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:5367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Mac: catalina 10.15.7

**Comment by JeremyDolle** [comment]
Verify that react native cli is not installed globaly and retry

**Comment by Angelk90** [comment]
@JeremyDolle : 
```
> react-native -v

react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```

**Comment by JeremyDolle** [comment]
You have to unistall react-native-cli
`npx` allow you to execute a command's package without install it globaly.So, you will always use the latest version.

**Comment by Angelk90** [comment]
@JeremyDolle : I uninstalled globally:
`npm install -g react-native-cli`
Thank you seems to work, but do not understand what the problem was that gave.

**Comment by JeremyDolle** [comment]
All right cool !

The explanatation is because of the version oh the react native cli installed globaly and in the New versions of react native it is not recommended anymore. You can find it in the [react native documentation](https://reactnative.dev/docs/environment-setup#react-native-command-line-interface).

**Comment by Angelk90** [comment]
@JeremyDolle : removing react-native-cli I can no longer auto-link modules:
`react-native link
`
Is there a solution?

**Comment by JeremyDolle** [comment]
`npx react-native link`

**Comment by ozanmanav** [comment]
Hi, In addition, you can use it to solve the problem.

`npx --ignore-existing react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

**Comment by slasho** [comment]
I have the same problem... and I I did remove react-native-cli

**Comment by slasho** [comment]
✨  Done in 31.99s.
yarn remove v1.22.18
[1/2] 🗑  Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
/Users/jcasanova/Documents/GIT/test/MyApp/node_modules/metro-hermes-compiler/src/emhermesc.js:77
          throw ex;
          ^

RuntimeError: abort(Error: ENOENT: no such file or directory, lstat '/Users/jcasanova/Documents/GIT/test/MyApp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/jcasanova/Documents/GIT/test/MyApp/node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:527:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)

Node.js v17.7.1
  │  ~/GIT/test 
