### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#133]
Hi @AurelGit, @JeremyDolle,

congratulations for the project, it would be possible to implement the following features:

- [ ] Change language

Since you are using `i18next`, it would be very useful if you could use the device language as the default primary language, let me explain.

We consider that we have three languages ​​supported in our app and they are: `en, it, es`
We assume our primary app language is `en`.
But our language of the device we are using is `it`.

What I recommend would be useful to be able to save the language, for example.
The first time you start the app, it takes the language of the device and checks if the following language is among those proposed, if so, use the language of the device, if the language of the device is not found, the default one is used that is `en` .

This would also allow in the future through a `select` to allow the user to select a different language, for example `es`, so the selected language is saved, the next time the app is used it is found.
If no language is selected, the default language is used.

- [x] Dark mode

Similar to the point above, only it refers to `Dark mode`.

First of all it would be useful to have a default `Theme` and a` Theme for Dark mode`, in reference you have colors.

So `Colors.primary` for both` Default` and `Dark mode`, so on.

If the device uses dark mode, then the first time you start the app it takes as settings to use colors for `Dark mode` if it doesn't use `Dark mode` then it uses `Default` colors, and this is saved what, so later if he wants to change the `Theme` independent if the device uses the `Dark mode` or not he can do it.

- [ ] Manage the different endpoints for dev, staging, production for api

For example:
```
yarn ios // (dev)
yarn ios -d // (dev)
yarn ios -s // (staging)
yarn ios -p // (production)
```

- [ ] Tailwind (`tailwind-rn`, `react-native-tailwindcss`, `react-native-tailwind`)

- [ ] Obfuscate code

- [ ] Examples of screens using react native paper

Example:
login page using SafeAreaView, signup, profile page, use of navigation drawer layout
It would be very useful to have a demo example of the app.

Additional queues:

- [ ] SplashScreen
- [ ] react-native-animated-tabbar
- [ ] react-native-app-intro-slider
- [ ] react-native-app-tour
- [ ] know if the device is connected to the internet (style youtube)
- [ ] Use of Pinned ShortCuts

**Comment by AurelGit** [comment]
Hey @Angelk90! Thank you for your message.

There is a lot a really good ideas! We have to read it carefully and discuss about it. 
We will put our discussion on this thread. 

Love your analyze thanks again.

**Comment by Angelk90** [comment]
@AurelGit : When you want to discuss it, I'm here, just tag me.

If the following features were implemented, it would give the opportunity to provide a complete product that touched on various scenarios.

**Comment by Angelk90** [comment]
@AurelGit , @JeremyDolle : 

To know the language of the device:
```
const deviceLanguage = (Platform.OS === 'ios'
    ? NativeModules.SettingsManager.settings.AppleLocale ||
      NativeModules.SettingsManager.settings.AppleLanguages[0]
    : NativeModules.I18nManager.localeIdentifier
  ).split('_')[0]; // Return a string: "en", "es", "it"
```

To know the scheme of the device:
```
import { Text, useColorScheme } from 'react-native';
const MyComponent = () => {
  const colorScheme = useColorScheme(); //Return a string or null: "light", "dark" or null(The user has not indicated a preferred color theme)
  return <Text>useColorScheme(): {colorScheme}</Text>;
};
```

**Comment by Angelk90** [comment]
@AurelGit , @JeremyDolle :  there are still many bugs, what do you think? 

![Registrazione schermo 2020-11-20 alle 16 57 17](https://user-images.githubusercontent.com/20476002/99822262-497ada00-2b53-11eb-9878-98d8223b54db.gif)

**Comment by JeremyDolle** [comment]
Hi nice job !

I actually working on dynamic themes and dark mode. It almost done, I just want to challenge the solution and improve it. After that I hope it will be added to the boilerplate if the solution seems good. See you soon

**Comment by Angelk90** [comment]
@JeremyDolle : I look forward to your solution.

**Comment by Angelk90** [comment]
@JeremyDolle : I don't know if it will be useful to you, this is the current version of what you saw in the gif.
If it can help you in any way: https://github.com/Angelk90/react-native-boilerplate-1

**Comment by JeremyDolle** [comment]
I close this issue, we now use the `Project tab` for todo tasks and, when we will be ready, we will create a dedicated issue to request "included feature wanted" from the community
