### ISSUE TITLE
File Gutters.js margin and padding all bottom

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#134]
Hi @AurelGit, @JeremyDolle, I was looking at the following file but I realized that all the references to the margin and padding are bottom, I would like to understand why.

https://github.com/thecodingmachine/react-native-boilerplate/blob/c85cc0748ab251de472eb9c4d65d9bc9ae346b80/template/src/Theme/Gutters.js#L24-L35

https://github.com/thecodingmachine/react-native-boilerplate/blob/c85cc0748ab251de472eb9c4d65d9bc9ae346b80/template/src/Theme/Gutters.js#L43-L54

**Comment by JeremyDolle** [comment]
Thanks for the report! it should be T for Top, L for Left and R for Right !! We will correct it soon
