### ISSUE TITLE
Remove bottom Tab.Screen

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#137]
Hi @AurelGit , @JeremyDolle : 

How do I remove that written "Home, with all the relative space occupied by the bottom tab.

<img width="374" alt="Schermata 2020-11-16 alle 21 23 17" src="https://user-images.githubusercontent.com/20476002/99303943-ff8fac80-2851-11eb-97ef-c98f6f24cff0.png">

**Comment by JeremyDolle** [comment]
Hi, simply replace the tab navigator by a stack navigator in `src/Navigator/Main.js`

**Comment by Angelk90** [comment]
@JeremyDolle :  Thank you, this is the only way, right?

P.s.
I'm trying dark mode, so whether it's enabled or not as seen from the gif.
But as you can see, the top and bottom remain white.

![Registrazione schermo 2020-11-16 alle 21 39 36](https://user-images.githubusercontent.com/20476002/99306052-e50b0280-2854-11eb-9a90-a941dd583fa6.gif)

Being that this problem comes from using SafeAreaView I was wondering the SafeAreaView at the beginning of the app what exactly it needs, what problems it solves.

Here a screen by removing SafeAreaView.

<img width="430" alt="Schermata 2020-11-16 alle 21 51 40" src="https://user-images.githubusercontent.com/20476002/99306869-0cae9a80-2856-11eb-8a28-5654e6e3b8f2.png">

**Comment by JeremyDolle** [comment]
Yes, this is the only way. 
You should keep the safe area to be able to use the bottom navigation for iPhone.
For the top you just have to set the status bar barStyle to dark-content. For the bottom try to move the safe area into the the NavigatorContainer like this in App.js :

```
<PersistGate loading={null} persistor={persistor}>
        <NavigationContainer ref={navigationRef}>
          <StatusBar barStyle="dark-content" />
          <SafeAreaView style={Layout.fill}> <ApplicationNavigator />
</SafeAreaView>
        </NavigationContainer>
    </PersistGate>
```

I actually working on this interesting feature too.

**Comment by Angelk90** [comment]
@JeremyDolle : It seems that the barStyle to dark-content only works on the text of the barStyle and not on its background.
As you indicated it seems not to work I had tried.

**Comment by JeremyDolle** [comment]
Did you try the `backgroundColor` props of the status bar ?

**Comment by JeremyDolle** [comment]
In the documentation the statusbar is into the safe area did you try it ?

**Comment by JeremyDolle** [comment]
Last question, for the bottom issue: did you use the dark theme [setup of react-navigation](https://reactnavigation.org/docs/themes/) ?

**Comment by Angelk90** [comment]
@JeremyDolle : 

Code App.js
```
import 'react-native-gesture-handler'
import React from 'react'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/lib/integration/react'
import { store, persistor } from '@/Store'
import { SafeAreaView, StatusBar, useColorScheme } from 'react-native'
import {
  NavigationContainer,
  DefaultTheme as NavigationDefaultTheme,
  DarkTheme as NavigationDarkTheme
} from '@react-navigation/native';
import {
  DarkTheme as PaperDarkTheme,
  DefaultTheme as PaperDefaultTheme,
  Provider as PaperProvider
} from 'react-native-paper'
import { ApplicationNavigator } from '@/Navigators'
import { navigationRef } from '@/Navigators/Root'
import { Layout } from '@/Theme'
import './Translations'

const PaperThemeDefault = {
  ...PaperDefaultTheme,
  colors: {
    ...PaperDefaultTheme.colors,
    primary: '#3498db'
  }
}

const PaperThemeDark = {
  ...PaperDarkTheme,
  colors: {
    ...PaperDarkTheme.colors,
    primary: '#3498db',
    background: '#222222'
  }
}

const CombinedDefaultTheme = {
  ...PaperDefaultTheme,
  ...NavigationDefaultTheme
}

const CombinedDarkTheme = {
  ...PaperDarkTheme,
  ...NavigationDarkTheme,
  colors: {
    ...NavigationDarkTheme.colors,
    background: '#303030',
    card: '#222222',
    text: '#ffffff'
  }
}

const App = () => {
  const colorScheme = useColorScheme()
  const isDark = colorScheme === "dark"
  const paperTheme = isDark ? PaperThemeDark : PaperThemeDefault
  const combinedTheme = isDark ? CombinedDarkTheme : CombinedDefaultTheme
  return (
    <Provider store={store}>
      {/**
       * PersistGate delays the rendering of the app's UI until the persisted state has been retrieved
       * and saved to redux.
       * The `loading` prop can be `null` or any react instance to show during loading (e.g. a splash screen),
       * for example `loading={<SplashScreen />}`.
       * @see https://github.com/rt2zz/redux-persist/blob/master/docs/PersistGate.md
       */}
      <PersistGate loading={null} persistor={persistor}>
        <PaperProvider theme={paperTheme}>
            <NavigationContainer ref={navigationRef} theme={combinedTheme}>
              <StatusBar barStyle={`${isDark ? 'light' : 'dark'}-content`} />
              <ApplicationNavigator />
            </NavigationContainer>
        </PaperProvider>
      </PersistGate>
    </Provider>
  )
}

export default App
```

**Comment by JeremyDolle** [comment]
With this code did you have trouble ?

**Comment by Angelk90** [comment]
@JeremyDolle : This code is what you see in the image proposed above, I'm not talking about the gif.

In fact it is without SafeAreaView.

**Comment by JeremyDolle** [comment]
I will check that but I recommend using the `AppearanceProvider` like it is recommended in the react navigation doc

**Comment by Angelk90** [comment]
@JeremyDolle : It only works on android -> https://reactnative.dev/docs/statusbar#backgroundcolor

**Comment by Angelk90** [comment]
@JeremyDolle : 

<img width="867" alt="Schermata 2020-11-17 alle 11 49 52" src="https://user-images.githubusercontent.com/20476002/99381068-11f9fc80-28cb-11eb-9cd6-44940ab1dd8e.png">

```
<PersistGate loading={null} persistor={persistor}>
        <PaperProvider theme={paperTheme}>
            <NavigationContainer ref={navigationRef} theme={combinedTheme}>
              <StatusBar barStyle={`${isDark ? 'light' : 'dark'}-content`} />
              <SafeAreaView style={[Layout.fill, { backgroundColor: isDark ? '#303030' : '#f2f2f2' } ]}>
                 <ApplicationNavigator />
               </SafeAreaView>
            </NavigationContainer>
        </PaperProvider>
      </PersistGate>
```

**Comment by JeremyDolle** [comment]
Thanks for your remarks @Angelk90 

I'll close this issue to try to discuss about only one issue in one ticket. 
Could you please try to follow the issue template available to help us to organize ?

See you

**Comment by Angelk90** [comment]
@JeremyDolle  :
Can I ask you to be more specific, I'm not sure I understand what you mean here:

Could you please try to follow the issue template available to help us to organize ?
