### ISSUE TITLE
Save storage information

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#138]
Hi @AurelGit , @JeremyDolle : 

If you want to save information such as language, theme type(light, dark), etc ...
Based on the structure of the boilerplate, what is the right approach (method) to follow in order to save this information.

Example:
I want to have the language to be used on the app selected from those available but I want to save this information, that is the language selected by the user in case he closes the app or reboots the device.

It would be possible to have an example, I don't find anything in the docs.

What I want to do is to be able to read an information in the storage and to be able to save an information.

**Comment by JeremyDolle** [comment]
You will need to use the `redux` and `redux-persist` with the `whiteList` props of `persistConfig` from [`src/Store/index.js`](https://github.com/thecodingmachine/react-native-boilerplate/blob/master/template/src/Store/index.js#L26). We just mention it [here](https://thecodingmachine.github.io/react-native-boilerplate/docs/ReduxStore#architecture) but you can find more information [here](https://github.com/rt2zz/redux-persist#blacklist--whitelist).

**Comment by Angelk90** [comment]
@JeremyDolle : I'm trying but with poor results, I'm not quite understanding how to make it work.
