### ISSUE TITLE
Strange problem when you start the app before you launch the Startup screen

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#143]
Hi @JeremyDolle , @AurelGit : 

![Registrazione schermo 2020-11-30 alle 13 16 37](https://user-images.githubusercontent.com/20476002/100610097-5f388e00-330f-11eb-93e7-adceb0caf81d.gif)

I noticed this thing, I would like to understand if it is normal what happens.

I gave it a try, changing the project logo.

When I start apps on `android`, before starting the` Startup` screen with the machine logo with the loader, you see a white screen with the app icon.

When I start app on `ios`, there is no white screen with the app icon, only a white screen.

I would like to understand if the reason is because app is in I think debug mode or not?

**Comment by JeremyDolle** [comment]
Hi, I am on it. Follow the [instructions](https://thecodingmachine.github.io/react-native-boilerplate/docs/Configuration) to change the splash screen style
