### ISSUE TITLE
Error in template

### ISSUE THREAD

**Issue by masterclin** [thecodingmachine/react-native-boilerplate#144]
in execution of command npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
Dont create structure

**Comment by JeremyDolle** [comment]
please follow this [link](https://github.com/thecodingmachine/react-native-boilerplate/issues/132#issuecomment-727197777). If it doesn't work please be more precise about you error.

**Comment by ozanmanav** [comment]
@masterclin Hi, In addition, you can use it to solve the problem.

npx --ignore-existing react-native init MyApp --template @thecodingmachine/react-native-boilerplate
