### ISSUE TITLE
Can not install template

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#145]
Trying to install with "npx react-native init myapp --template @thecodingmachine/react-native-boilerplate" commanda.

But it returns:

nhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat `'/Users/blabla/works/myapp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'`

My versions are:
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

I uninstall both, and Installed react-native-cli globally.
But nothing changed.

what could be problem?

**Comment by JeremyDolle** [comment]
Hi, you have not to install react-native-cli globally. So uninstall it and use `npx`. For the explanation, `npx` allow you to run commands of a package without installing it. So nowadays using `npx` allow you to run the `init` command with the latest version of react-native-cli
Let me know if it's ok

**Comment by tcagkansokmen** [comment]
thanks for your answer, it worked.
