### ISSUE TITLE
Can not work with expo

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#146]
I'm trying to use that boilerplate with expo.

I installed expo with "npm install expo".
I go to "index.js" and change it like below;

```
import { AppRegistry } from 'react-native'
import { registerRootComponent } from 'expo';
import App from './src/App'
import { name as appName } from './app.json'

registerRootComponent(App)
```

and used "expo start"
It returns an error like;

"Tried to register two views with the same name RNCSafeAreaProvider"

What could be the solution?

**Comment by JeremyDolle** [comment]
Hi @tcagkansokmen, This boilerplate is not thinks to work with expo. All I can do is redirect you to the [expo documentation section](https://docs.expo.io/bare/using-expo-client/) and pay attention to the "What are the limitations?" section.

**Comment by tcagkansokmen** [comment]
Hi there,

I solved that with remove safe-area-view and reinstall it with expo.

`expo install {package what u need} --npm
`
is the answer.
