### ISSUE TITLE
How to change StatusBar backgroundcolor, for specific pages?

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#150]
Hi there,

Statusbar color is assigned on root file like;

```
 <PersistGate loading={null} persistor={persistor}>
      <SafeAreaView style={{ flex: 0, backgroundColor: '#3b7a99' }} />
      <SafeAreaView style={[Layout.fill, { backgroundColor: '#fff' }]}>
        <NavigationContainer ref={navigationRef}>
          <StatusBar barStyle="dark-content" backgroundColor="#3b7a99" />
          <ApplicationNavigator />
        </NavigationContainer>
      </SafeAreaView>
    </PersistGate>
  </Provider>
```

But, I want to change it when I open drawer (my header is black, but drawer is white. so when drawer is opened, statusbar makes trouble)

**Comment by JeremyDolle** [comment]
Hello, yes the boilerplate provides only a simple utilisation of the statusbar. If you want to go futher (especially with drawer) please refer to the documentation of [react natigation statusbar section](https://reactnavigation.org/docs/status-bar/)
