### ISSUE TITLE
Cannot create new project by using command in documents

### ISSUE THREAD

**Issue by bunthondev** [thecodingmachine/react-native-boilerplate#151]
**Describe the bug**
I followed instruction how to install this boilerplate, unlucky i got blank react native project after followed that.

**To Reproduce**
I run command `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`
and follow all instruction in `https://thecodingmachine.github.io/react-native-boilerplate/docs/Installation`

**Expected behavior**
I assume boilerplate theme and example code will be in my project, but actually i got blank react native original code.

**Comment by JeremyDolle** [comment]
Hi, did you start the metro bundler ? and did you have any logs in there ?

**Comment by JeremyDolle** [comment]
I close due to inactivity
