### ISSUE TITLE
How to reset "Redux Toolkit variable"

### ISSUE THREAD

**Issue by tcagkansokmen** [thecodingmachine/react-native-boilerplate#158]
My term may be wrong but.

I want to reset values after I use em.

Here's my page:

```
const products = useSelector((state) => state.product.search)

  const addBasketProduct = (id) => {
    setSearch('')
    dispatch(GetProduct.action(id))
  }

```
Here's my store:

```
import {
  buildAsyncState,
  buildAsyncReducers,
  buildAsyncActions,
} from '@thecodingmachine/redux-toolkit-wrapper'
import fetchAll from '@/Services/Product/GetService'

export default {
  initialState: buildAsyncState('GetService'),
  action: buildAsyncActions('search/GetService', fetchAll),
  reducers: buildAsyncReducers({
    itemKey: 'service',
    errorKey: 'GetService.error', // Optionally, if you scoped variables, you can use a key with dot notation
    loadingKey: 'GetService.loading',
  }),
}

```

I want to reset "state.product.search" value, after I use it.
How can this be possible?

**Comment by JeremyDolle** [comment]
I don't understand what you want by reset after using it. But if you want a search state just for one screen, I recommend you to use a local state by using `const [search, setSearch] = useState('')`. If you want this search value across screens, you will have to create an action for setting a value to the search state key. For this, you will not have to use redux-toolkit-wrapper but redux-toolkit (no needing of `pending`, `fulfilled` and `rejected` state). Am I clear ? Let me know if you don't understand what I am saying I will try to be more precise 😉

**Comment by JeremyDolle** [comment]
Close due to inactivity
