### ISSUE TITLE
Unhandled error on Android devices. 

### ISSUE THREAD

**Issue by Qwevo** [thecodingmachine/react-native-boilerplate#159]
Error shows when we press the return button on an Android device.

**To Reproduce**

1. Open the app on the android emulator, wait until it loads to home screen.
2. Click on back button (<) on android until you get back to launch screen.
3. Open the app again.
4. Error shows in a toast message : **The action 'RESET' with payload {"index":0,"routes":[{"name":"Main"}]} was not handled by any navigator.**

**Expected behavior**
Reopen the app works without any issue.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/41085331/103746321-3471e180-5001-11eb-93b6-f818882d98d0.png)

**Desktops**
 - OSx 11.x - Ubuntu 18.04 LTS 

**Smartphone**
 - Device: Android emulator.
 - OS: 9.0

**Comment by JeremyDolle** [comment]
Thanks for the report, I will fix it

**Comment by Qwevo** [comment]
@JeremyDolle  please let us informed about the progress of this fix, thank you.

**Comment by crisemcon** [comment]
I'm having the same issue:(
