### ISSUE TITLE
Can't remove the The Coding Machine Icon

### ISSUE THREAD

**Issue by ariannargesi** [thecodingmachine/react-native-boilerplate#167]
Hey Guys
I just created an empty project using react-native-boilerplate and I deleted all the files within the folders (Also TOM.png).
But When I load the app I can still see this red octopus in the middle of the page.
What should I do?

**Comment by JeremyDolle** [comment]
Hi @ariannargesi, the octopus is also present on android and iOS native splash screens. See this [doc](https://thecodingmachine.github.io/react-native-boilerplate/docs/Configuration#change-the-splash-screen-icon) section 😉.

**Comment by ariannargesi** [comment]
Hi @JeremyDolle, Problem Solved. Thank you very much
