### ISSUE TITLE
Navigate after dispatched action has been handled

### ISSUE THREAD

**Issue by jeremyhalin** [thecodingmachine/react-native-boilerplate#173]
I want to navigate to `Auth` navigator after dispatching a `Logout` action.
How to navigate just after action has been dispatched and reduced? 

Here is my service (I have async code to execute, that's why I use async action):
```javascript
import * as Keychain from 'react-native-keychain'

export default async (param, dispatch) => {
  await Keychain.resetInternetCredentials('access_token')
  await Keychain.resetInternetCredentials('refresh_token')

  return {
    ...dispatch.getState().user.item,
    connected: false,
    email: '',
  }
}
```

Action:
```javascript
import {
  buildAsyncState,
  buildAsyncReducers,
  buildAsyncActions,
} from '@thecodingmachine/redux-toolkit-wrapper'
import LogoutUserService from '@/Services/User/Logout'

export default {
  initialState: buildAsyncState('logout'),
  action: buildAsyncActions('user/logout', LogoutUserService),
  reducers: buildAsyncReducers({
    errorKey: 'logout.error',
    loadingKey: 'logout.loading',
  }),
}

```

Logout button onPress:
```javascript

  const logout = () => {
    Alert.alert(
      t('settings.logout'),
      t('settings.logoutConfirmation'),
      [
        {
          text: t('settings.cancel'),
          style: 'cancel',
        },
        {
          text: t('settings.confirm'),
          onPress: () => {
            dispatch(Logout.action())
            navigate('Auth', { screen: 'IndexAuth' })
          },
        },
      ],
      { cancelable: true },
    )
  }
```

`AuthNavigator`
```javascript
import React, { useEffect } from 'react'
import {
  IndexAuthContainer,
  RegisterAuthContainer,
  LoginAuthContainer,
} from '@/Containers'
import { createStackNavigator } from '@react-navigation/stack'
import { useSelector } from 'react-redux'
import { navigateAndSimpleReset } from '@/Navigators/Root'

const Stack = createStackNavigator()

// @refresh reset
const AuthNavigator = () => {
  const userConnected = useSelector((state) => state.user.item.connected)

  useEffect(() => {
    if (userConnected) {
      navigateAndSimpleReset('Main')
    }
  }, [userConnected])

  return (
    <Stack.Navigator>
      <Stack.Screen
        name="IndexAuth"
        component={IndexAuthContainer}
        options={{
          headerShown: false,
        }}
      />
      <Stack.Screen name="RegisterAuth" component={RegisterAuthContainer} />
      <Stack.Screen name="LoginAuth" component={LoginAuthContainer} />
    </Stack.Navigator>
  )
}

export default AuthNavigator
```

Problem is, I dispatch an async action, so when user arrives on `IndexAuth`, state `user.connected` is still `true` and he is redirected back to `Main` navigator.

**Comment by JeremyDolle** [comment]
Did you try to navigate in the logout service thanks to the navigation service ?

**Comment by jeremyhalin** [comment]
I think I did, but navigating **before** reducer returns new state shouldn't work no?
Because use will be redirected, but state would still be `user.connected: true`

I will try tomorrow but it's kind of a hack isn't it?
Did you never encounter this use case? How do you handle logging out your users? 😊

Thanks!

**Comment by jeremyhalin** [comment]
I tried to `navigate` to `Auth` navigator just before `return` in the service, but it didn't work. State is updated **after** user is redirected to `AuthNavigator`, so it thinks that user is still connected and redirect to `MainNavigator`.

I found a solution though. I just discovered that we can `await` for dispatch, and it seems to work so well! Does it wait for the action to be processed by reducer?

```javascript
const logout = () => {
  Alert.alert(
    t('settings.logout'),
    t('settings.logoutConfirmation'),
    [
      {
        text: t('settings.cancel'),
        style: 'cancel',
      },
      {
        text: t('settings.confirm'),
        onPress: async () => { // make the onPress async
          await dispatch(Logout.action()) // add `await` to the dispatch call
          navigate('Auth', { screen: 'IndexAuth' }) // this should be called only when action is dispatched/reduced?
        },
      },
    ],
    { cancelable: true },
  )
}
```

**Comment by JeremyDolle** [comment]
I understand your issue, I will try on personnal project but it's clearly detailled [here](https://redux-toolkit.js.org/api/createAsyncThunk#unwrapping-result-actions) we can await the dispatch. The thing you have to know is in redux-toolkit-wrapper we use the rejectWithValue options and you have a very nice exemple (the second one) [here](https://redux-toolkit.js.org/api/createAsyncThunk#examples). I will check if the toolkit wrapper do its job correctly
