### ISSUE TITLE
Throwing an error from within the action

### ISSUE THREAD

**Issue by limdev92** [thecodingmachine/react-native-boilerplate#175]
Im trying to throw an error from within a service action, catching then it with a classic try catch clause, like this:

```
 useEffect(() => {
    const callAction = async () => {
      try {
        await dispatch(Test.action());
        console.warn('SUCCESS!!!');
      } catch (e) {
        console.warn('ERROR!!!');
        console.warn(e);
      }
    };
    callAction();
  }, []);

```    
  

_Store\Test.js_
  
```
const Test = {
  initialState: buildAsyncState('test'),
  action: buildAsyncActions('test/test', testService),
  reducers: buildAsyncReducers({
      errorKey: 'test.error', // Optionally, if you scoped variables, you can use a key with dot notation
      loadingKey: 'test.loading',
      itemKey: null,
    }),
  };
  
export default Test;

```

_Service\Test.js_

```
export default async (arg, thunkAPI) => {
  throw new Error('TEST');
};

```

**Comment by JeremyDolle** [comment]
Can you share me how did you create your action ? with only these code sections I can't help you

**Comment by limdev92** [comment]
> Can you share me how did you create your action ? with only these code sections I can't help you

I updated the question by adding more code

**Comment by JeremyDolle** [comment]
Ok just look at this [reply](https://github.com/thecodingmachine/react-native-boilerplate/issues/173#issuecomment-770879742) , it will redirect you on the redux-toolkit doc were it's written that `The thunks generated by createAsyncThunk will always return a resolved promise with either the fulfilled action object or rejected action object inside, as appropriate.` And you have a nice example (link in the same reply) on how to handle it. Let me know if it's help 😉

**Comment by limdev92** [comment]
Ah yes, that's right.
Just in case someone encounters the same difficulty, the right way to catch the error should be like this:
```
useEffect(() => {
    const callAction = async () => {
        const testResult = await dispatch(Test.action());
        if(Test.action.rejected.match(testResult)) console.warn('ERROR!!!');
        else console.warn('SUCCESS!!!');
    }
    callAction();
}, []);
```

**Comment by JeremyDolle** [comment]
Exactly ! I close the issue 😉
