### ISSUE TITLE
Boiler plate code creation command failing on my mac machine

### ISSUE THREAD

**Issue by shubhambathe1** [thecodingmachine/react-native-boilerplate#176]
So I was trying to get the boilerplate code by the command provided in readme section of repository:-

`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

But the command is failing after some initial processing on terminal. Here is the error message that I am getting:-

Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:11389) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/webwerks/Desktop/tmp/MyApp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'.

Attaching terminal screenshot for reference.

<img width="1279" alt="Screenshot at Feb 11 18-05-57" src="https://user-images.githubusercontent.com/31159892/107637500-38de8980-6c94-11eb-910c-33fa46ef3dbf.png">

Please let me know if I am doing anything wrong, thanks in advance.

**Comment by JeremyDolle** [comment]
See #145
