### ISSUE TITLE
I can install it on windows

### ISSUE THREAD

**Issue by vijaydivakar6** [thecodingmachine/react-native-boilerplate#183]
Windows  React Native[](url)
![errorr](https://user-images.githubusercontent.com/42201799/113310197-9a7eb400-9325-11eb-8905-e117ebe58ad8.JPG)

Please let me know.

**Comment by JeremyDolle** [comment]
The problem seems to be because of the react navigation package. See [here](https://github.com/react-native-masked-view/masked-view/issues/111#issuecomment-809039803).

**Comment by JeremyDolle** [comment]
@vijaydivakar6 did you try with yarn ?

**Comment by JeremyDolle** [comment]
any update @vijaydivakar6 ?
