### ISSUE TITLE
How to upgrade 

### ISSUE THREAD

**Issue by ha-family** [thecodingmachine/react-native-boilerplate#184]
hi, i'm working on a project start with this great boilerplate since V1
but i'm wondering to know, how to upgrade?
because i always reopen a project every time this project has a new tag
it looks like a bad idea ...

**Comment by JeremyDolle** [comment]
Hi @ha-family, 

At this time, I am not providing any update plan for every update except for [upgrading from V1] (https://thecodingmachine.github.io/react-native-boilerplate/docs/Migrating ). For small updates what I recommend is to get into the diffs of each version where you are late. For example, if you are in 2.2.4 and want to upgrade to 2.2.5, just go to [here](https: //github.com/thecodingmachine/react-native-boilerplate/compare/v2.2.5 ... master) and you will see the differences. The most important things to upgrade are the dependencies!
