### ISSUE TITLE
src folder not generated

### ISSUE THREAD

**Issue by mamta-deswal** [thecodingmachine/react-native-boilerplate#186]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JeremyDolle** [comment]
Please fill the template issue. I can't help you with just an issue title

**Comment by mamta-deswal** [comment]
Already have react native setup now i run this command:- npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
After success , i opened the project but there is no src folder as described in doc:- https://thecodingmachine.github.io/react-native-boilerplate/docs/Introduction

**Comment by JeremyDolle** [comment]
That's strange 😳
Let's try to find what's happening.

- First what do you mean when you said `already have a react-native setup`? You mean you have the required setup for react-native development ? Or you mean you already have an opened react-native project ?

- Verify you don't have react-native-cli installed locally by running `react-native -v`.

- What's your environment ? MacOS, Windows or Linux ?

**Comment by mamta-deswal** [comment]
Hi,

Already react native setup means, react-native environment set up in my
macbook.
I used this boilerplate before 2 months also, it's very nice and no problem
come at that time. but I think due to some update architecture issue in
it's project directory.

My system config:-
MacBook Air (Retina, 13-inch, 2018)
macOs(Mojave), version-10.14.5.




Thanks & Regards,
Mamta Deswal
Software Developer
8750648334, 9034927471

**Comment by JeremyDolle** [comment]
Ok that's really weird, I try the command and it's working for me. 
You said that you have no error during the initialization ? If you have trouble on this step it's maybe more related to the react-native-cli init command but I don't see any issue like this...

Do you remember the version that's work ?

**Comment by mamta-deswal** [comment]
After running this command:- npx react-native init MyApp --template
@thecodingmachine/react-native-boilerplate

Please check your folder there will be not src folder, I tried in three mac
but it's not working.



Thanks & Regards,
Mamta Deswal
Software Developer
8750648334, 9034927471

**Comment by JeremyDolle** [comment]
Please take a look, it's seems to work

https://user-images.githubusercontent.com/15814069/113509482-1d865100-9556-11eb-97b8-2cb8032d965f.mp4

Try the use the pre-release version, maybe you will have more chance : 
```
npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate@v3.alpha.1
```

**Comment by RogerByte** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Just remember to npm uninstall -g react-native-cli and yarn global add @react-native-community/cli so you have new features during starting a new project

**Comment by JeremyDolle** [comment]
> > **Describe the bug**
> 
> > A clear and concise description of what the bug is.
> 
> > 
> 
> > **To Reproduce**
> 
> > Steps to reproduce the behavior:
> 
> > 
> 
> > 1. Go to '...'
> 
> > 2. Click on '....'
> 
> > 3. Scroll down to '....'
> 
> > 4. See error
> 
> > 
> 
> > **Expected behavior**
> 
> > A clear and concise description of what you expected to happen.
> 
> > 
> 
> > **Screenshots**
> 
> > If applicable, add screenshots to help explain your problem.
> 
> > 
> 
> > **Desktop (please complete the following information):**
> 
> > 
> 
> > * OS: [e.g. iOS]
> 
> > * Browser [e.g. chrome, safari]
> 
> > * Version [e.g. 22]
> 
> > 
> 
> > **Smartphone (please complete the following information):**
> 
> > 
> 
> > * Device: [e.g. iPhone6]
> 
> > * OS: [e.g. iOS8.1]
> 
> > * Browser [e.g. stock browser, safari]
> 
> > * Version [e.g. 22]
> 
> > 
> 
> > **Additional context**
> 
> > Add any other context about the problem here.
> 
> 
> 
> Just remember to npm uninstall -g react-native-cli and yarn global add @react-native-community/cli so you have new features during starting a new project

Good remarks. Plus, no need to reinstall it ! Thanks to npx you can use the cli without install it globally so no extra time to update this global dependency.

**Comment by JeremyDolle** [comment]
@mamta-deswal any update ?
