### ISSUE TITLE
Eslint issue

### ISSUE THREAD

**Issue by naicky-whiterain** [thecodingmachine/react-native-boilerplate#187]
BTW, i want to give props to people who made this boilerplate. one of the best!

I just have an issue when running this script "yarn lint", is says
" Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » @react-native-community/eslint-config#overrides[1]': Cannot find module 'typescript'".

Although im not planning to use typescript and this boilerplate doesn't support it yet. I just want to know if there's a workaround here when running this script. Thank you and appreciate your response.

**Comment by JeremyDolle** [comment]
Sorry I missed my last release 🥺

Try to check your eslint config, if there is something about typescript remove it. Remove `node_modules` and `yarn.lock` and run a `yarn` command. Let me know ! 

I will correct it as soon as possible !

**Comment by naicky-whiterain** [comment]
Hi @JeremyDolle,

Thank you for your quick response, appreciate it!

I did all the steps you've mentioned, however the same error is still displaying everytime im executing the lint script.

**Comment by JeremyDolle** [comment]
What version of the boilerplate you have ?

**Comment by naicky-whiterain** [comment]
"version": "2.2.5" the latest

**Comment by JeremyDolle** [comment]
Ok found 😭 !! You probably have `Config/index.ts` file just delete it, sorry for the issue I will correct it in the next release !!

**Comment by naicky-whiterain** [comment]
@JeremyDolle It worked! Appreciate for the fast response! Thank you so much!
