### ISSUE TITLE
Console error on ios

### ISSUE THREAD

**Issue by naicky-whiterain** [thecodingmachine/react-native-boilerplate#189]
Hi @JeremyDolle ,

I'd like to report an console error i'm encountering whenever I'm running ios. Please see steps to reproduce and attached screenshots. Thank you in advance. 

Steps to reproduce:
1. install the boilerplate
2. run yarn start
3. run yarn ios

![Screen Shot 2021-04-22 at 9 02 56 PM](https://user-images.githubusercontent.com/56329702/115718926-2f695000-a3ae-11eb-806b-107e9f0eb3b1.png)
<img width="1369" alt="Screen Shot 2021-04-22 at 9 03 04 PM" src="https://user-images.githubusercontent.com/56329702/115718939-32644080-a3ae-11eb-98d1-4eb790d257d8.png">

**Comment by JeremyDolle** [comment]
Hi @naicky-whiterain, do you have the `src/Config/index.js` file with this content ?
```
export const Config = {
  API_URL: 'https://jsonplaceholder.typicode.com/',
}
```

**Comment by naicky-whiterain** [comment]
Hi @JeremyDolle ,

yes confirmed. i haven't change anything yet on the boilerplate, as I'm preparing it for our team to use. probably this one causes?
