### ISSUE TITLE
warn Failed to clean up template temp files

### ISSUE THREAD

**Issue by ArnauKokoro** [thecodingmachine/react-native-boilerplate#191]
**Describe the bug**
When doing npx to start a new project from the template having the following error:

```
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.

node:fs:1130
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, lstat '${ProjectFolder}/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'
```

It says "This is not a critical error, you can work on your app." but on the package json I don't have the dependencies.

**To Reproduce**
1. npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate

**Expected behavior**
Installation completes at expected

** Screenshoot **

<img width="544" alt="Captura de pantalla 2021-04-30 a las 11 58 19" src="https://user-images.githubusercontent.com/80262126/116679912-5d9cf000-a9ab-11eb-8dbd-8e474cfcabc5.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.2

**Additional context**
I did an installation 2 days ago and it did works. But doing a new project from template today and it doesn't work.

Many Thanks!!

**Comment by JeremyDolle** [comment]
That's really weird!! 😳

Did you try multiple time ?
did you have react-native-cli installed globally ?

**Comment by ArnauKokoro** [comment]
Yes, I tried multiple time.

I do have react-native-cli installed globally.

**Comment by JeremyDolle** [comment]
You have to unistall react-native-cli like it's recommended in the documentation. It may cause unexplicable issues like this one. See [#190](https://github.com/thecodingmachine/react-native-boilerplate/issues/190#issuecomment-827101432). Let me know 😉

**Comment by ArnauKokoro** [comment]
It works!! Many Thanks!!
