### ISSUE TITLE
Documentation website code syntax

### ISSUE THREAD

**Issue by Hophoet** [thecodingmachine/react-native-boilerplate#192]
First i want to thank all the contributors of this amazing boilerplate,  i'm currently reading the docs and it is very clean
THANK YOU :+1: 

**Syntax error **  https://thecodingmachine.github.io/react-native-boilerplate/docs/Theme at Image section
`const { Images } useTheme()`

**Expected syntax**
`const { Images } = useTheme()
`

**Comment by JeremyDolle** [comment]
Hi @Hophoet ! Thanks for your feedback! We appreciate 😀

Yes you're right, thanks! Do you want to make a merge request?

**Comment by Hophoet** [comment]
Yes, with pleasure
