### ISSUE TITLE
Error When Install

### ISSUE THREAD

**Issue by hendrawaan** [thecodingmachine/react-native-boilerplate#193]
I got some error when installing it. Can you solve this problem?
![image](https://user-images.githubusercontent.com/47717089/116774868-b0e57000-aa89-11eb-97fe-53a26cdaba6d.png)

**Comment by JeremyDolle** [comment]
Please look into other related issue [here #190](https://github.com/thecodingmachine/react-native-boilerplate/issues/190#issuecomment-827101432)

**Comment by hendrawaan** [comment]
it's been 5 months since I used RN so, I don't know if there's any update about it. Thank you so much
