### ISSUE TITLE
Failed to create the project by using this template

### ISSUE THREAD

**Issue by joe-tan** [thecodingmachine/react-native-boilerplate#194]
**Describe the bug**
I tried to create a project by using the command but failed with the error.

**To Reproduce**
1. Go to the terminal on Mac OS (Catalina Version 10.15.4).
2. Run "npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate"
3. See an error, creating was stopped due to the error.

**Expected behavior**
Without any error, the project should be created.

**Screenshots**
![image](https://user-images.githubusercontent.com/57562940/118066855-072fa880-b3d2-11eb-8d6c-6078fe7a9430.png)
![image](https://user-images.githubusercontent.com/57562940/118066948-2c241b80-b3d2-11eb-845a-b9e28b48cd76.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina Version 10.15.4
 - node: 13.12.0
 - react-native-cli: 2.0.1

**Comment by JeremyDolle** [comment]
Hi @joe-tan you find your solution ? Don't forget, you have to uninstall react native cli globaly
