### ISSUE TITLE
Add react-native icons library

### ISSUE THREAD

**Issue by amir-al-razin** [thecodingmachine/react-native-boilerplate#196]
**Is your feature request related to a problem? Please describe.**
***I'm always frustrated when configuring icons library in react-native***

**Describe the solution you'd like**
***configuring react-native-vector-icons library would be a better plus point in our daily workflow***

**Comment by JeremyDolle** [comment]
If I understand well, you want this library included by default in the boilerplate ?

**Comment by amir-al-razin** [comment]
> If I understand well, you want this library included by default in the boilerplate ?

Yes

**Comment by JeremyDolle** [comment]
Sorry but the philosophy of this boilerplate is to avoid extra dependencies. I know, this library need time but I can't force all users or potential user to use it.

Plus, if it's present, do I have to install all fonts ? If I do that, I literally add a lot of potentially not used stuff. If I install only one font I will have to create a documentation section about adding or removing a font. If I do a documentation section about this, I will have to follow the icon library version update and also potentially get some issues related the the dependency

Hope you understand 😊
