### ISSUE TITLE
Invalid state key : item in startup/init/fulfilled this appears when i dispatch the startup action

### ISSUE THREAD

**Issue by panwar67** [thecodingmachine/react-native-boilerplate#199]
How can i use the payload when the action is completed
Invalid state key : loading in smartshala/fetchSSS/pending
Invalid state key : error in smartshala/fetchSSS/pending
Invalid state key : item in startup/init/fulfilled

I keep getting all these when i use buildAsyncReducers

**Comment by JeremyDolle** [comment]
Hi @panwar67 can your share me your piece of code related to fetchSSS please ?
Your error seems to be related to your state generation. The buildAsyncState and the buildAsyncReducers seems to not understand the same state.

For your information, I currently working on a better API more understandable for the redux-toolkit-wrapper. It will be cool and easier I hope 🤞

**Comment by JeremyDolle** [comment]
close due to inactivity
