### ISSUE TITLE
[docs] "Don't code sign" no longer an option in Xcode

### ISSUE THREAD

**Issue by JakubOrsula** [thecodingmachine/react-native-boilerplate#200]
**Describe the bug**
According to guide at https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/ option `Don't code sign` should be selected in `Signing` as Debug Code Signing Entity. However there is no such option present Xcode 12.

**To Reproduce**
1. Go to Xcode
2. Click on `Build settings`
3. Scroll down to `Signing`
4. Select `Code Signing Entity`
5. There is no `Don't code sign option`

**Expected behavior**
Guidance on what should be done if this option is not present. I don't know if it is my fault that it is not there, but here is [SO question](https://stackoverflow.com/questions/52602009/xcode-10-where-is-the-dont-code-sign-option-in-code-signing-identity) describing the same problem. Answer is to use other method. Docs should mention this or switch from don't sign to other option as default.

**Aditional Info**
Runnning apps still works even if we force the text `Don't code sign`. However it works with iOS Distribution as well and doesn't give errors in `Signing & Capabilities` tab.

**Comment by JeremyDolle** [comment]
Hi @JakubOrsula, this part of the documentation is obsolete for the moment, that's why we marked it as "work in progress".
The fact that putting "don't code sign" in release signin it's not recommended, now Xcode is more magic and can download or generate some certificates. So, in debug you have to put an Apple developpement and in release an Apple distribution. After that you can create your beta lane

**Comment by JakubOrsula** [comment]
Thanks for getting back to me. I got it to work, however it cost me few minutes. This documentation is still being linked to from official fastlane docs https://docs.fastlane.tools/getting-started/cross-platform/react-native/. I don't know if someone is working on it, I can add a few lines explaining what to do and open PR. Would that be okay?

**Comment by JeremyDolle** [comment]
Of course you can make a PR ! With pleasure ! 😊
