### ISSUE TITLE
Can't install on windows 10. Could not resolve dependency

### ISSUE THREAD

**Issue by 1mike12** [thecodingmachine/react-native-boilerplate#201]
**Describe the bug**

**To Reproduce**
1. npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate

**Expected behavior**
installs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10

**Smartphone (please complete the following information):**
n/a

```
- 📚 If you need to read more about this boilerplate : https://thecodingmachine.github.io/react-native-boilerplate/
- 🤕 If you have some troubles : https://github.com/thecodingmachine/react-native-boilerplate/issues
- ⭐ If you love this boilerplate, give us a star, you will be a ray of sunshine in our lives :) https://github.com/thecodingmachine/react-native-boilerplate
(node:25824) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
√ Executing post init script
× Installing dependencies
error Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: boilerplate@3.0.0
npm ERR! Found: react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.0" from redux-flipper@1.4.2
npm ERR! node_modules/redux-flipper
npm ERR!   redux-flipper@"^1.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by JeremyDolle** [comment]
Please look into other related issue [here #190](https://github.com/thecodingmachine/react-native-boilerplate/issues/190#issuecomment-827101432)

**Comment by 1mike12** [comment]
I didn't install globally, just running `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate` like instructed

**Comment by 1mike12** [comment]
@JeremyDolle  can you re-open?

**Comment by JeremyDolle** [comment]
Sorry for closing this issue ! 😇 Can you give me the version of npm and/or yarn ?
If you run `yarn install` or `npm install` after getting this error ? What's happening ?

After running `react-native -v` what's happening ?

**Comment by 1mike12** [comment]
npm -v = 7.11.2

So I never actually saw anywhere I had to install react-native natively, but I did and ran the version and got:
react-native -v
error: unknown option `-v'

If I cd into the MyApp directory, and run npm install I get the same error: 
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: boilerplate@3.0.0
npm ERR! Found: react-native@0.64.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.64.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.63.0" from redux-flipper@1.4.2
npm ERR! node_modules/redux-flipper
npm ERR!   redux-flipper@"^1.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\1mike\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\1mike\AppData\Local\npm-cache\_logs\2021-06-09T21_28_03_312Z-debug.log
```

**Comment by 1mike12** [comment]
Hmm, I think this must be a problem with my version of NPM. I guess in npm 7 they got super serious about matching peer dependency versions. https://stackoverflow.com/a/66620869

Solution for me to at least get started was to just pass --legacy-peer-deps. Maybe another alternative is to just downgrade to npm 6? Because I'm not sure if running `npm i --legacy-peer-deps` after a failed template install gets me to the same end state as if it never failed?

**Comment by JeremyDolle** [comment]
Ok... maybe try to update npm to the latest version or use yarn instead (seems to have less issues)

**Comment by muhaimincs** [comment]
still happening on npm 8. I use yarn instead
