### ISSUE TITLE
Boilerplate and SQLite

### ISSUE THREAD

**Issue by Cortlandd** [thecodingmachine/react-native-boilerplate#204]
Hello, for my specific project, I need SQL /SQLite (likely https://github.com/andpor/react-native-sqlite-storage) as opposed to AsyncStorage for relational object purposes. What would be best approach for database initialization and running queries? `Application.js` for initializing the databse? My initial thinking was for each service, instead of making API calls, initialize the SQLite object and run a query with the necessary values. But not sure or handling results. Any direction? Potentially return a boolean as my itemKey to denote if a query ran accordingly? But all theory. I wanted feedback if possible?

**Comment by JeremyDolle** [comment]
Hi @Cortlandd, sorry for the delay. I am not an SQLite user, so if I understand well SQLite will be a local database included in the app ?
By the way, what do you want to do with it ? bind it with Redux ?

**Comment by Cortlandd** [comment]
Yes. I want to store data locally on the device for offline purposes. Given the complexity of the data, I don't think asyncstorage will suffice.

Following this guide: https://implementationdetails.dev/blog/2020/05/03/react-native-offline-first-db-with-sqlite-hooks/ as well for a more proper implementation but getting the following error. It has something to do what the return value when startup finishes.

```
A non-serializable value was detected in the state, in the path: `startup.error`. Value: [Error: useConversationsContext must be used within a ConversationContextProvider] 
Take a look at the reducer(s) handling this action type: startup/init/rejected.
```

**Comment by Cortlandd** [comment]
I figured out the off topic above. But question about using queries inside service and or store still remains. Recommendation?
