### ISSUE TITLE
Flipper Bug - Suggested Fix

### ISSUE THREAD

**Issue by Asher978** [thecodingmachine/react-native-boilerplate#205]
In case if anyone runs into `flipper bug` which I encountered.
You will need to update your `Podfile` with the following

``` js
// add this
use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

// remove this
use_flipper!()
```

[Suggested Here From Flipper](https://github.com/facebook/flipper/issues/2215#issuecomment-828837100)

**Comment by Cicko** [comment]
I am still having an Error during building related to the Flipper library
```c++
Flipper-Folly/folly/portability/Time.h:52:17: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
```

**I SOLVED IT BY UPDATING THE PODS** 
`pod install --repo-update`

The output was:
```sh
> Installing Flipper 0.87.0 (was 0.75.1)
> Installing Flipper-Folly 2.5.3 (was 2.6.7)
> Installing Flipper-RSocket 1.3.1 (was 1.4.3)
> Installing FlipperKit 0.87.0 (was 0.75.1)
> Removing Flipper-Boost-iOSX
> Removing Flipper-Fmt
```

Now I can build the Boilerplate without bugs 🔥

**Comment by Asher978** [comment]
> I am still having an Error during building related to the Flipper library
> 
> ```c++
> Flipper-Folly/folly/portability/Time.h:52:17: Typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
> ```
> 
> **I SOLVED IT BY UPDATING THE PODS**
> `pod install --repo-update`
> 
> The output was:
> 
> ```shell
> > Installing Flipper 0.87.0 (was 0.75.1)
> > Installing Flipper-Folly 2.5.3 (was 2.6.7)
> > Installing Flipper-RSocket 1.3.1 (was 1.4.3)
> > Installing FlipperKit 0.87.0 (was 0.75.1)
> > Removing Flipper-Boost-iOSX
> > Removing Flipper-Fmt
> ```
> 
> Now I can build the Boilerplate successfully!

I did not mention in my first message. pod update will be required after changing the pod file :)
