### ISSUE TITLE
Question: How to deal with flatlist datasource

### ISSUE THREAD

**Issue by rodwin** [thecodingmachine/react-native-boilerplate#21]
Hi,
You might have an idea on how to supply the data source for a flat list component. Redux state returns a list of map instead of array of object which is causing flatlist not to render

`<FlatList
            keyExtractor={(item) => item.ID}
            style={{ backgroundColor: Colors.white, paddingHorizontal: 15 }}
            data={this.state.listings}
            extraData={this.state.listings}
            // renderItem={this.renderUserGroup}
            renderItem={({ item }) => (
              <View>
                <Text>test</Text>
              </View>
            )}
          />`

`const mapStateToProps = (state) => {
  // console.log('state.listings.get(listings)', state.listings.get('listings'))
  return {
    fetching: state.listings.get('fetching'),
    listings: state.listings.get('listings'),
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    getListings: () => dispatch(ListingActions.listingRequest()),
  }
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(AllListingScreen)`

console log of data shows its a list
![image](https://user-images.githubusercontent.com/208163/49674570-4eb1fc00-fad7-11e8-8b30-5c8b449ce0ee.png)

Appreciate if you can shed some light.
Thanks.

**Comment by AurelGit** [comment]
Hello @rodwin !

Try to convert your `List` into an `array` inside `mapStateToProps`, with : 
``` javascript
listings: state.listings.get('listings').toJS(),
```

Be sure to initialize your list in the `InitialState.js` file with a `List()` (imported from immutable) to avoid some warnings.
For example : 
```javascript
import { Map, List } from 'immutable'

/**
 * The initial values for the redux state.
 */
export const INITIAL_STATE = Map({
  fetching: false,
  listings: List(),
})
```

Hope this will help you !

**Comment by rodwin** [comment]
@AurelGit This solves the issue. I didn't saw this appraoch googling this issue. Thanks for this.
