### ISSUE TITLE
ReactJs Boilerplate

### ISSUE THREAD

**Issue by hassancoul** [thecodingmachine/react-native-boilerplate#211]
Hi, I'm a big fan of the react-native boilerplate and I can't thank you enough for the work you do.

I think it would be really cool to have a ReactJs boilerplate with a structure relatively close to the React-Native boilerplate that takes PWA into account.

**Comment by JeremyDolle** [comment]
Hi @hassancoul 👋 
Thanks for your comment.
For the moment we don't plan to make the ReactJS side because it could be hard to maintain all our repositories and we have a lot of ideas for this repository. I keep your issue opened for now because in the future we could make it 😉 who knows ? 🤫

**Comment by JeremyDolle** [comment]
will be reopen if the subject came back
