### ISSUE TITLE
"@" import is not working inside Visual Studio Code 

### ISSUE THREAD

**Issue by AzadKshitij** [thecodingmachine/react-native-boilerplate#212]
**Describe the bug**
"@" import is not working inside Visual Studio Code 
`jsconfig.js` 
```js
// This configuration is used for IDE completion with the babel-plugin-module-resolver plugin
// eslint-disable-next-line no-undef
System.config({
  paths: {
    "@/*": "./src/*",
  },
})
``` 
 
**To Reproduce**
Try to import file with @ import style 

**Expected behavior**
I expect vscode to give some intellisense about the import.

**Screenshots**
![ebda6ad73cc1bb7f7b9bade1dcd1ebaaf0991d63](https://user-images.githubusercontent.com/54288405/127735077-39799668-84a1-463a-aa1d-460a5762bf62.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: -

**Smartphone (please complete the following information):**
 - Device: google pixel
 - OS: android
 - Browser -
 - Version -

**Additional context**
when I try to use `jsconfig.json` it also gives error

**Comment by JeremyDolle** [comment]
Hi @AzadKshitij can you try to replace your jsconfig content with:

```
{
  "compilerOptions": {
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}
```

**Comment by JeremyDolle** [comment]
Close due to inactivity
