### ISSUE TITLE
Multiple Item Objects In Redux Store

### ISSUE THREAD

**Issue by erayaras** [thecodingmachine/react-native-boilerplate#215]
Hi,

Thank you for the repo. It makes my life easier.

I got a question;

I have following store on Redux:

    {
      "forgotPassword": {
        "item": {
          "error": "ok",
          "params": {
            "email": "test@asd.com"
          },
        },
        "fetchEmail": {
          "loading": false,
          "error": null
        },
        "fetchChangePassword": {
          "loading": false,
          "error": null
        }
      },
      "_persist": {
        "version": -1,
        "rehydrated": true
      }
    }

But I want my store like this:

*The difference is `item` object is there for both `fetchEmail` and `fetchChangePassword` objects.*

    {
      "forgotPassword": {
        "fetchEmail": {
          "item": {
              "error": "ok",
              "params": {
                  "email": "test@asd.com"
              },
          },
          "loading": false,
          "error": null
        },
        "fetchChangePassword": {
          "item": {
              "error": "ok",
              "params": {
                  "email": "test@asd.com"
              },
          },
          "loading": false,
          "error": null
        }
      },
      "_persist": {
        "version": -1,
        "rehydrated": true
      }
    }

This is my file structure;

    Store
    --ForgotPassword
    ----FetchEmail.js
    ----FetchChangePassword.js
    ----index.js
    --index.js

------------------

Store files:

    //FetchEmail.js
    export default {
      initialState: buildAsyncState('fetchEmail'),
      action: buildAsyncActions('forgotPassword/fetchEmail', fetchEmailService),
      reducers: buildAsyncReducers({
        errorKey: 'fetchEmail.error', 
        loadingKey: 'fetchEmail.loading',
      }),
    }

-------------

    //FetchChangePassword.js
    export default {
      initialState: buildAsyncState('fetchChangePassword'),
      action: buildAsyncActions('forgotPassword/fetchChangePassword', fetchChangePasswordService),
      reducers: buildAsyncReducers({
        errorKey: 'fetchChangePassword.error',
        loadingKey: 'fetchChangePassword.loading',
      }),
    }

------------

    //ForgotPassword/index.js
    
    import FetchEmail from './FetchEmail'
    import FetchChangePassword from './FetchChangePassword'
    
    
    const sliceInitialState = {
      item: {},
    }
    
    export default buildSlice('forgotPassword', [FetchEmail, FetchChangePassword], sliceInitialState).reducer

-----------------

I have tried following changes:
    
Changed item objects accordingly.

    //ForgotPassword/index.js
    const sliceInitialState = {
      itemEmail: {},
      itemChangePassword: {},
    }

Added following to my `reducers`:

    //FetchFetch.js
    itemKey: 'fetchChangePassword.itemFetch',
    
    //FetchChangePassword.js
    itemKey: 'fetchChangePassword.itemChangePassword',

None of them worked.

How can I add `item` object to my reducers separately?

**Comment by JeremyDolle** [comment]
Hi and thanks for your feedback !
I think you are on the right way! 
Try to set your `sliceInitialState` like this :

```
const sliceInitialState = {}
```

 You slice like this :

```
export default buildSlice('forgotPassword', [FetchEmail, FetchChangePassword], sliceInitialState).reducer
```

And your modules like this:

//FetchEmail
```
export default {
  initialState: {fetchEmail:{item:null, loading: false, error:null}},
  action: buildAsyncActions('forgotPassword/fetchEmail', fetchEmailService),
  reducers: buildAsyncReducers({
    itemKey: 'fetchEmail.item',
    errorKey: 'fetchEmail.error', 
    loadingKey: 'fetchEmail.loading',
  }),
}
```

And 

//FetchChangePassword.js
```
export default {
  initialState:  {fetchChangePassword:{item:null, loading: false, error:null}},
  action: buildAsyncActions('forgotPassword/fetchChangePassword', fetchChangePasswordService),
  reducers: buildAsyncReducers({

  itemKey: 'fetchChangePassword.item',
    errorKey: 'fetchChangePassword.error',
    loadingKey: 'fetchChangePassword.loading',
  }),
}
```

Let me know 😉

**Comment by erayaras** [comment]
Thank you for your answer.

If server returns error, I can get the error like this:
`  const fetchForgotPasswordError = useSelector(
    state => state.forgotPassword.fetchEmail.error,
  )`

But still I cannot access to `item` with following:
`  const fetchForgotPasswordError = useSelector(
    state => state.forgotPassword.fetchEmail.item,
  )`


If server returns success, the error like this:
`Possible Unhandled Promise Rejection (id: 1):
TypeError: undefined is not an object (evaluating 'acc[key]')`

Do you know what could be the problem?

**Comment by JeremyDolle** [comment]
Did you register you slice correctly by adding it in the root reducer ? Like this :


```
//src/Store/index.js

...

import startup from './Startup'
import theme from './Theme'

import forgotPassword from './ForgotPassword' <-- your new reducers

const reducers = combineReducers({
  startup,
  theme,
  forgotPassword, <-- add this line

})

...

```

**Comment by JeremyDolle** [comment]
Can you give me the stack trace of the error ?

**Comment by erayaras** [comment]
I registered it as you mentioned above.

Here is stack trace of the error from Chrome DEV toolsr:

` backend.js:32 Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'item' of undefined
TypeError: Cannot read property 'item' of undefined
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:118924:17
    at Array.reduce (<anonymous>)
    at getNestedValue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:118923:30)
    at stateKeyExists (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:118907:16)
    at fulfilled (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:118866:74)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:117798:22
    at produce (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:116416:17)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:117797:20
    at Array.reduce (<anonymous>)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.erayaras.secureApp:117773:27
n @ backend.js:32
registerWarning @ LogBox.js:118
warnImpl @ LogBox.js:64
console.warn @ LogBox.js:37
onUnhandled @ promiseRejectionTrackingOptions.js:43
onUnhandled @ rejection-tracking.js:71
(anonymous) @ JSTimers.js:231
_callTimer @ JSTimers.js:123
callTimers @ JSTimers.js:379
__callFunction @ MessageQueue.js:414
(anonymous) @ MessageQueue.js:113
__guard @ MessageQueue.js:365
callFunctionReturnFlushedQueue @ MessageQueue.js:112
(anonymous) @ debuggerWorker.aca173c4.js:4
`

**Comment by erayaras** [comment]
I made typo:
` itemKey: 'fet -hc- ChangePassword.item'`

Thank you for your time, it's working correctly.
