### ISSUE TITLE
Failure to run iOS. Code 65, 70

### ISSUE THREAD

**Issue by huncrew** [thecodingmachine/react-native-boilerplate#218]
***
Error when running 'yarn ios'

_''Found Xcode workspace''_

BUT first time running it, gives error code 65, second code 70.

***Replication

- Follow instructions
- Install all dependencies as per the react-native website (all of them)
- Run Yarn start (to start Metro)
- Run Yarn ios... gives errors.

**Comment by JeremyDolle** [comment]
Hi @huncrew,
I thinks your error comes from your environment.
1. Verify you don't have react-native installed globally 
2. Check update about Xcode 
3. Check your version of flipper (should be the same of the one in the pod file)
4. Did you have install another dependency or is it a blank project from the boilerplate ?

If nothing works, try to remove the `node_modules` and do a `yarn install` again (saw in related react-native issues)

If nothing works, please give me your stacktrace.

**Comment by huncrew** [comment]
Hi Jeremy,

Thank you for responsing.

I thought at first it could be because im on an M1. But i switched to rosetta on xcode and reactnative awesomeproject now works.

Il complete further checks today. 

Thank you

**Comment by huncrew** [comment]
Its a blank project, i havent changed anything

**Comment by huncrew** [comment]
I dont think i have a pod file though

**Comment by JeremyDolle** [comment]
So the problem was the M1 ?

**Comment by huncrew** [comment]
Yarn start is throwing errors now, and it's saying react native isn't a command either. 

Deleted the folder. Recloning the repo to try again, if not will give up, taking too much time.

**Comment by huncrew** [comment]
Yeah, something wrong with the whole thing, fails to even install now

**Comment by JeremyDolle** [comment]
Hi @huncrew there is something wrong with your installation.
I need your environment setup and steps to reproduce, a stack trace or something for helping you...

- You said you clone again the repository, you talk about your project repository not the boilerplate ?
- if an error said react native is not a command anymore means you don't run `yarn install` to install react native as a dependency.
- be sure to follow the instructions (here)[https://thecodingmachine.github.io/react-native-boilerplate/docs/Installation]

This is the first time someone cames with these issues so I need a maximum of information to help you.
The M1 can came with its issues and specificities.

**Comment by huncrew** [comment]
Hi Jeremy,
Sorry I will be more specific.

I had already created a repo here on github of this boilerplate and created some branches and a text file.

I didn't want to start again so I wanted to clone the repo (ive made no changes to the boilerplate, just added a text-file)

Okay so I'm starting all over again - here are my steps, im writing these as I do it.

1. I have cloned the boiler plate code via my repo
2. I run Yarn install

_Below are the results:_

dalegrant@Dales-MacBook-Air Reactful % yarn install
yarn install v1.22.11
warning ../../package.json: No license field
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 0.99s.
dalegrant@Dales-MacBook-Air Reactful % yarn start
yarn run v1.22.11
warning ../../package.json: No license field
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by huncrew** [comment]
The package.json file is pretty empty it has no start command within it, you can see that here in the github repo

**Comment by JeremyDolle** [comment]
You can't clone this repository because it's not a react-native architecture ! It's made to be used with react-native-cli. 
Please, read the documentation, it says simply run 

```
npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
```
To create a react native app using this boilerplate 

`MyApp` will be the name of your application. 

So please tell me if you still have issue by applying this step

**Comment by huncrew** [comment]
Okay my apologies. 

It's now working! I suspect the M1 had something to do with it, as no react-native project has worked first time on this laptop.
I've had to enable Rosetta, reinstall each project, or find a work around.

Okay, so the project has to be setup using  the react-native-cli for it work, understood.

If anything broke again, I would have to fix my problems locally, and then push to my github repo.
