### ISSUE TITLE
Sample app not working correctly for Android  - A non-serializable value was detected in an action, in the path: `payload`. Value: 

### ISSUE THREAD

**Issue by sahilengati** [thecodingmachine/react-native-boilerplate#219]
Sample app not working correctly for Android. IOS working perfectly .

A non-serializable value was detected in an action, in the path: `payload`. Value: 

npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate
cd MyApp
yarn start
yarn android 

A non-serializable value was detected in the state, in the path: `user.fetchOne.error`. Value: [TypeError: undefined is not an object (evaluating '_ref$response.data')] 

![image](https://user-images.githubusercontent.com/88997412/129507375-be539529-c0e9-494b-8952-685fe6adda64.png)

**Comment by sahilengati** [comment]
also checked i dont have react native cli installed

**Comment by sahilengati** [comment]
I was able suppress the error
serializableCheck : false  

But now it's not able to read it as an object ? 
Also new to mobile dev so forgive me if its obvious 

![image](https://user-images.githubusercontent.com/88997412/129520988-44455f00-5aec-438f-94a9-e9b5768bd3e6.png)

**Comment by JeremyDolle** [comment]
Hi @sahilengati, do you change anything in the `Config/index.js` file ?
This append on Android only ?

**Comment by sahilengati** [comment]
Not really . Yes , ios works correctly

**Comment by JeremyDolle** [comment]
What do you means by `Not really ` ?

**Comment by sahilengati** [comment]
Its means no :) . I guess we can close this as i have created a project from start and so far it has effected only me. Thanks
