### ISSUE TITLE
App crashes immediately (Android)

### ISSUE THREAD

**Issue by tstkenny** [thecodingmachine/react-native-boilerplate#22]
I am quite new to the repo and I cannot make it work on API 23 emulator or a physical Android 5 device. The app crashes once loaded, without any react native red background error. Would appreciate if you can take a look. Remote debugger shows nothing since the RN is not loaded yet I suspect.

react-native run-android completes without any error in console though.

React Native Environment Info:
System:
OS: Windows 10
CPU: x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Memory: 7.60 GB / 15.96 GB
Binaries:
Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 5.3.0 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.1.0.0 AI-173.4907809

**Comment by tstkenny** [comment]
I got some progress.. if u do NOT rename the project by yarn, you can actually see RN's red background error screen with "Unable to connect with remote debugger"

**Comment by tstkenny** [comment]
I found that the gradle API level is 26 so make sure your environment complies.

Next step is to press Ctrl-M in android emulator -> Dev settings, put localhost:8081, then close all cmd boxes and restart.

Viola!  It's working!

**Comment by Zefau** [comment]
I'm facing the same issues renaming the project using `yarn rename`:

```
$ react-native-rename xxxxx
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
\android\app\src\main\res\values\strings.xml MODIFIED
\index.js MODIFIED
\package.json MODIFIED
\app.json MODIFIED
\android\settings.gradle MODIFIED
\app.json MODIFIED
The system cannot find the path specified.
\android\app\BUCK MODIFIED
\android\app\build.gradle MODIFIED
\android\app\src\main\AndroidManifest.xml MODIFIED
Done removing previous bundle directory.
Done removing builds.
APP SUCCESSFULLY RENAMED TO "homii"! 🎉 🎉 🎉
```

With this, the app crashes immediately at startup.

**Comment by JeremyDolle** [comment]
Hi @Zefau ! Please check if all occurences are successfully renamed in : 

**Commun**
* `App/index.js`:
```javascript
...
AppRegistry.registerComponent('XXXXXX', () => App)
```
* `App/app.json` :
```javascript
{
  "name": "XXXXXX",
  "displayName": "XXXXXX"
}
```

**Android**
* `/android/settings.gradle` :
```java
rootProject.name = 'XXXXXX'
...
```
* `/android/app/src/main/java/com/[yourprojectname]/MainActivity.java`:
```java
...
/**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "XXXXXX";
    }
...
```

**iOS**
* `app/ios/[YourProjectName]/Info.plist` :
```xml
...
<key>CFBundleDisplayName</key>
<string>XXXXXX</string>
...
```
* `app/ios/[YourProjectName]/AppDelegate.m` :
```
...
RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"XXXXXX"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];
...
```

Make sure that you restart your Metro Bundler and rebuild the App.

**Comment by Zefau** [comment]
The project name is updated in the following files
- `App/index.js`
- `App/app.json`
- `/android/settings.gradle`

But the file `MainActivity.java` gets deleted once renaming the project. Thus `/android/app/src/main/java/com/[yourprojectname]/MainActivity.java` does not exist.

When I copy and edit the files manually, it works.

**Comment by AurelGit** [comment]
Thanks for the PR ! ❤️ 

Yes can you please create a dedicated issue to this problem ?
