### ISSUE TITLE
Update React-Navigation to v6

### ISSUE THREAD

**Issue by arunim2405** [thecodingmachine/react-native-boilerplate#220]
Update React-Navigation to v6 and modify the example navigation accordingly

**Comment by JeremyDolle** [comment]
Hello @arunim2405 😊 This is in work in progress with the update of react native too ! You will have it really soon 😉

**Comment by arunim2405** [comment]
> Hello @arunim2405 😊 This is in work in progress with the update of react native too ! You will have it really soon 😉

How soon? :P I need to start a production app soon. Please let me know if you guys need any help :)

**Comment by arunim2405** [comment]
Thanks for the update, are there any specific steps I need to take to upgrade to these versions, using rn 64.2 with react navigation v6 
@JeremyDolle

**Comment by JeremyDolle** [comment]
I just publish the 3.0.3 version of the boilerplate ! you can look the [files changes](https://github.com/thecodingmachine/react-native-boilerplate/pull/225/files) of the release
