### ISSUE TITLE
Installation does not create files

### ISSUE THREAD

**Issue by baninaveen** [thecodingmachine/react-native-boilerplate#222]
While installing the `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate` it does not create src folder as well as does not ask for typescript

**Comment by JeremyDolle** [comment]
Hi @davesidious, do you have react-native cli installed locally. If yes, please remove it like it said in the react native documentation. See [208](https://github.com/thecodingmachine/react-native-boilerplate/issues/208#issuecomment-876950136)
