### ISSUE TITLE
[Question] Component Styling

### ISSUE THREAD

**Issue by Gabsys** [thecodingmachine/react-native-boilerplate#228]
Hi, I am new to this boilerplate and I am wondering, should all the component styles go into `Theme -> components` folder and later be imported in `Common.js`? 
Because not all components are common, some are more of a page-specific component and I find it weird to have them be in Common.js 🤔

**Comment by JeremyDolle** [comment]
Hello @Gabsys,

It's a good question, in the boilerplate we don't make page-specific components, only pure component with utility first style. Btw, using the theme functions is important for the multi theming. So, if you want to create a new theme file for page-specific components do it and don't forget to add it into the useTheme :wink:. Adapt the boilerplate for you, it could be better than ever !

Any other question, just ask 😃 !
