### ISSUE TITLE
[Android] Splashscreen flash in between navigation

### ISSUE THREAD

**Issue by Gabsys** [thecodingmachine/react-native-boilerplate#240]
Does anyone faces this issue where in between stack navigation, it flashes the splash screen for a sec before going into the destination screen? Only happens on Android

**Comment by Gabsys** [comment]
It was a React Navigation animation behavior on android. Fixed it by adding :
```
cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
```
to `screenOptions` of `<Stack.Navigator>`

**Comment by Gabsys** [comment]
Ultimately, the splashscreen is still behind the app. When I have an input and the input is moving up on press, making space for keyboard, I can also see the splashscreen appear 1 sec before keyboard is fully loaded.

**Comment by JeremyDolle** [comment]
Ok I heard about it, I will check it !
