### ISSUE TITLE
null object reference on android app

### ISSUE THREAD

**Issue by lyqht** [thecodingmachine/react-native-boilerplate#246]
After I started the app on android, I get the following error
![Screenshot_1640019879](https://user-images.githubusercontent.com/35736525/146804908-b83c2028-a09d-4ebc-8ef6-646a2f5e58ac.png)

Looking around, it seems to be an [existing issue](https://github.com/software-mansion/react-native-reanimated/issues/270) of the reanimated library, is there any solution by thecodingmachine team to get past it? Or is a downgrade of this library necessary to get the boilerplate working?

**Comment by JeremyDolle** [comment]
Hi @lyqht, the pinned issue is an old one. Maybe we've made a mistake, let's try to find it.

First, during the installation, did you choose Js or Ts ?
Second, did you modify the code before running on you device ?
Third, what device do you use ?

**Comment by loscsol** [comment]
Hi @lyqht , had the same problem on Android and I solved following ReactNativeReanimated's installation guide here:
[https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/#android)

Maybe that instructions have to be added to this repo too.

**Comment by lyqht** [comment]
Hello both, thanks for the help! For @JeremyDolle , here are my specifications
- Typescript project 
- without any code modification
- Android Pixel 3A simulator running on android API 30

after following @loscsol 's advice to check out the setup, the app works now without error! 🎉 
I have also made a PR to reflect those additional setup required for android.
