### ISSUE TITLE
Flipper crashes the app

### ISSUE THREAD

**Issue by lyqht** [thecodingmachine/react-native-boilerplate#248]
Out of curiosity to play with all the features that the boilerplate offers, I downloaded Flipper to try debugging the app. The app fails to start at all, and the error I got is the same as reported [here](https://github.com/facebook/flipper/issues/3189) in the flipper issue. 

The team can consider upgrading the flipper dependency when they release the fix later today :)

**Comment by Angelk90** [comment]
@lyqht : Try to see if with the new release it gives you the same problem.

**Comment by lyqht** [comment]
may I ask how do i upgrade to the latest boilerplate without creating a new project?

**Comment by JeremyDolle** [comment]
You can use the [compare release](https://docs.github.com/en/repositories/releasing-projects-on-github/comparing-releases) feature of github. Just compare your version to the latest one. It may works.

**Comment by lyqht** [comment]
I have tried it but there I couldn't make a PR from the new changes. Is there any other way to upgrade an existing project that was created from a previous boilerplate to use the latest boilerplate? say for a simple npx command?

**Comment by JeremyDolle** [comment]
You have to do the change one by one. The react-native-cli does not provide any cmd for that and the boilerplate neither. It's because it's too difficult and impossible without breaking the app. The boilerplate provides an architecture example that you can modify, if such a command exists, how to detect that you have change the default bottom bar navigation by a drawer ? Simply impossible. That's why I recommend you to use the compare tags of GitHub that look like the [react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/).

Maybe we can develop something like this in the documentation to help ? What do you think ?

**Comment by Angelk90** [comment]
@lyqht :

- Try to recreate a project from scratch
- Copy the files located in your src dir to the new project in src
- See if there are any problems

**Comment by lyqht** [comment]
Hi @Angelk90 , thank you for providing the steps. I see an error at the end of initializing the project.

```bash
✔ Downloading template
✔ Copying template
✔ Processing template
✔ 📘 Using typescript ? (y/N)

 … yes
⠴ Executing post init script
⠦ Executing post init script

TheCodingMachine React-Native Boilerplate initialized with success ! 🚀

                                                                    .-`    `::
 `/////////////     `/shhhy+-   ://.        /sy/                   /ss/   :NMN:
 `sssssyhhhyhhy:` `yMMMMNNMMMd. osss:     `hMMMh-    .-`         `+ss:   +MMm/.
      :MMM+----. `mMMm+:-`.oo/` osssyo`  `dMMMMh-   ohhh-       `oyy+-  sMMd/.
      :MMM+`     oMMN/-         osssyhs`.mMMMMMh-   -hds`      .syy+- `hMMh:`
      :MMM+`     hMMd:          oss-ohhhMMMhdMMh-    `.       +NNm/. .dMMy:`
      :MMM+`     oMMN/          oss-`shdMMd:dMMh-    :-`     sMMd/. -NMMo-
      :MMM+`     `mMMm/`  `/+:. oss- `sdMd:.hMMh-   hMys-  `hMMh:` -hdy-`
      :MMM+`      `yMMMMdssss+  oss.  `oh/- hMMh-   -hyo:  dMMs:` -ss+`
      .oys:`        .+yhyo/-    -::`    ``  -syo-     ..`  +mo-   `//
        ``             ```                    ``            `.
THE TYPESCRIPT VERSION 📘


- 📚 If you need to read more about this boilerplate : https://thecodingmachine.github.io/react-native-boilerplate/
- 🤕 If you have some troubles : https://github.com/thecodingmachine/react-native-boilerplate/issues
- ⭐ If you love this boilerplate, give us a star, you will be a ray of sunshine in our lives :) https://github.com/thecodingmachine/react-native-boilerplate
✔ Executing post init script
✖ Installing dependencies
error Error: spawn yarn ENOENT
```

However, I do see the new project folder being created. So I just tried starting the app. Now it no longer crashes 🎉 And i also can see the app from Flipper.

![image](https://user-images.githubusercontent.com/35736525/149462669-8e9147e6-427f-4f96-80fa-273961312d92.png)

**Comment by JeremyDolle** [comment]
@lyqht, happy to see that flipper doesn't crash anymore. For the error about the initialization it's located in the react native cli. Few ideas on what it could come from:
- You have react native cli installed globally and its not the lastest version
- the version of nodeJs is causing the issue
- maybe verify that you have yarn installed

If it's an known issue don't worry it's not bloking, simply run `yarn` and `cd ios && pod install`
