### ISSUE TITLE
Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 66

### ISSUE THREAD

**Issue by muhaimincs** [thecodingmachine/react-native-boilerplate#251]
**Describe the bug**
I try to use simulator on macos and this is what I got
![image](https://user-images.githubusercontent.com/30996641/147675705-733573b5-33df-40ba-a41e-a83c4b93b966.png)

**To Reproduce**
1. `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

**Expected behavior**
A simulator should run usual with app opened

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1
 - node: 16
 - npm: 8
 - simulator: 13.2
 - xcode: 13.2.1
 

**Additional context**
```bash
objc[13648]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x20876f130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10679c2c8). One of the two will be used. Which one is undefined.
objc[13648]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x20876f180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10679c318). One of the two will be used. Which one is undefined.
** BUILD FAILED **


The following build commands failed:
	Ld /Users/mcsdev/Library/Developer/Xcode/DerivedData/MyApp-awgefowcnwxvevcchywvfktxcjyl/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal (in target 'MyApp' from project 'MyApp')
(1 failure)
```

**Comment by yumsquare** [comment]
I had the exact problem. It was probably an m1 Mac issue.
The following solution fixed it for me.

https://stackoverflow.com/questions/66369650/undefined-symbol-protocol-descriptor-for-swift-expressiblebyfloatliteral-issu

**Comment by JeremyDolle** [comment]
I am on vacations, but I will make a new version with all dependencies up to date and I know that there is a method added for M1 issues in the PodFile. Hope it will fix this kind of issues

**Comment by JeremyDolle** [comment]
For the first message `Unable to boot...` : I have it also but it compiles and lauched even if this message is present. 

For the fact that the build failed : I update the boilerplate today see if the issue is still here

**Comment by JeremyDolle** [comment]
feel free to reopen
