### ISSUE TITLE
Update to version of React Native v0.66 and others

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#252]
**Is your feature request related to a problem? Please describe.**
Greater support for new versions of Android 12 and iOS 15.
Better Support for Apple Silicon, Xcode 13.
Hermes 0.9.0

P.s.
Happy Holidays.

**Additional context**
<img width="1413" alt="Schermata 2021-12-30 alle 16 10 05" src="https://user-images.githubusercontent.com/20476002/147763879-a45765fc-620f-4851-a164-79bd9a715193.png">

**Comment by JeremyDolle** [comment]
Hi @Angelk90, the update of all dependencies will be released after my holidays 😉

**Comment by Angelk90** [comment]
Hi @JeremyDolle , It would be possible to update with the latest version of the modules.

template/package.json
<img width="1403" alt="Schermata 2022-01-24 alle 17 52 35" src="https://user-images.githubusercontent.com/20476002/150828112-533776d0-56e1-4c86-876f-d3489c60f8d4.png">
<img width="1412" alt="Schermata 2022-01-24 alle 17 53 34" src="https://user-images.githubusercontent.com/20476002/150828127-4a6d58a4-b1de-4916-bbd9-c61600664596.png">

package.json
<img width="1407" alt="Schermata 2022-01-24 alle 17 54 49" src="https://user-images.githubusercontent.com/20476002/150828149-0c902c5e-b295-44e3-a4f4-5f8bdc69f20c.png">
<img width="1409" alt="Schermata 2022-01-24 alle 17 54 37" src="https://user-images.githubusercontent.com/20476002/150828139-997e7237-8c5d-4cbe-b5c4-fd2c3e42566f.png">

**Comment by JeremyDolle** [comment]
Yes I will
