### ISSUE TITLE
Error while Cloning Template and Running project.

### ISSUE THREAD

**Issue by premdasvm** [thecodingmachine/react-native-boilerplate#264]
Hi team,

I tried cloning the template using

`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`

but it's showing an error like this,

<img width="1440" alt="Screenshot 2022-01-17 at 4 07 28 PM" src="https://user-images.githubusercontent.com/14838550/149754583-e75b2e84-ca3c-488c-9abf-d7d47bf0d7a6.png">

also after this when I run the application, it's showing the default RN template, without any redux or anything, am I doing something wrong here.?

Is this the expected Project structure.?

<img width="286" alt="Screenshot 2022-01-17 at 4 11 22 PM" src="https://user-images.githubusercontent.com/14838550/149754935-42215c92-c1bc-4096-831b-1368b0aaed82.png">

**Comment by JeremyDolle** [comment]
Hi @premdasvm, why did you don't use a provided issue template ? 

Please make sure to don't have `react-native-cli` installed globally

**Comment by premdasvm** [comment]
Hi @JeremyDolle , `react-native-cli` is installed globally, 

and I ran `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate` this only, isn't this supposed to get the template also.?
