### ISSUE TITLE
[BUG]: Template doesn't work successfully from Documentation

### ISSUE THREAD

**Issue by thertzelle** [thecodingmachine/react-native-boilerplate#266]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Followed the usage instructions, when it goes to build the xcode project it fails. The error inside xcode says that it's missing a swift file, added an empty swift file and then the project runs successfully.

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MyApp.xcworkspace.
```
Within Xcode:
```
Undefined symbol: __swift_FORCE_LOAD_$_swiftDataDetection
Undefined symbol: __swift_FORCE_LOAD_$_swiftFileProvider
```
Add an empty .swift file to the project, and then the project builds within xcode...i get a screen with the project logo on it and all that stuff....But the project will still not build with `yarn ios`

### Version

latest

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

Monterey

**Comment by thertzelle** [comment]
Interesting. `npx react-native init MyApp --template react-native-template-typescript` works just fine though. I do not have an M1.

**Comment by JeremyDolle** [comment]
I will go deeper in your issue.

The react-native-typescript template is really really light...

Maybe it's related with Pods.

Did you have any trouble with Android ?
