### ISSUE TITLE
[BUG]: Creating a second service 

### ISSUE THREAD

**Issue by nicolabortignon** [thecodingmachine/react-native-boilerplate#267]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

This is, most likely, a very trivial mistake on my end. 

I've just checked out 3.2.4.

I want to create a second Service, and, as first step I've just duplicated the Services/modules/users folder and renamed into Services/modules/myservice. I've also adjust the object name in the index.js to reflect it, and change the path to the API endpoint in the fetchOne.js

At this point, when compiling, I get a message that the endpoints in one of the modules is overlapping with the one in the other. It seems like there is no segregation between the two objects 
`
api.injectEndpoints({
  endpoints: build => ({
    getUser: fetchOne(build),
  }),
  overrideExisting: false,
})
`

What I'd expect is that the modules here are creating segregation between the two objects,
which would mean:
users->getUser 
myservice->getUser 
can coexist. 

If I change the name of the endpoint (from getUser to getMyUser), 
something weird happens when initialising the store. If I inspect this bit of code in (Store/index.js)
`
const reducers = combineReducers({
  theme,
  ...Object.values(modules).reduce(
    (acc, module) => ({
      ...acc,
      [module.reducerPath]: module.reducer,
    }),
    {},
  ),
})
`
The object modules has the following structure: 

  `"userApi": {"endpoints": {"getMyUser": [Object], "getUser": [Object]},`

rather than  
`"userApi": {"endpoints": {"getUser": [Object]}} ", "myServiceAPI": {"endpoints": {"getMyUser": [Object]}} ",`
 

Am I missing something ? 

### Version

3.2.4

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

OSX 14.2

**Comment by JeremyDolle** [comment]
Hi @nicolabortignon, I hope I understand your problem.

To my mind, the tree should look like this:
```
src
  Services
    modules
      users
        fetchOne.js
        index.js
      myservice
        fetchOne.js
        index.js
      api.js
```

With the following: 

### src/Services/modules/index.js
```
export { userApi } from './users'
export { myServiceApi } from './myservice'
```

### src/Services/modules/myservice/fetchOne.js
```
export default build =>
  build.query({
    query: id => `/myservice/${id}`,
  })
```

### src/Services/modules/myservice/fetchOne.js
```
import { api } from '../../api'
import fetchOne from './fetchOne'

export const myServiceApi = api.injectEndpoints({
  endpoints: build => ({
    fetchOne: fetchOne(build),
  }),
  overrideExisting: false,
})

export const { useLazyFetchOneQuery } = myServiceApi
```
⚠️ the const need to be myServiceApi 

I think you let `userApi` in `src/Services/modules/myservice/fetchOne.js`

**Comment by nicolabortignon** [comment]
This roughly solved my issue. Thank you. 

Long story:  I did a bit of refactoring to understand what was really going on under the hood (RTK hides a lot of complexity), and figured I had some visibility clash with the reducer objects when they were combined in the state. 
From there i realised that, as you correctly pointed out that myServiceApi needs to have a different name as it is globally exported.

Thank you
