### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: Build apk for each release

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#270]
### Is your feature request related to a problem?

Whenever a release is released, it would be nice for a sample apk to be generated so that you can get a general idea of the sample project.

### Describe the solution you'd like

Use the github actions, which every time a release is released, a sample apk is generated.

**Comment by Angelk90** [comment]
@JeremyDolle : Are there any news?

**Comment by JeremyDolle** [comment]
Please be patient, the custom plugin will arrived it's a big feature.
