### ISSUE TITLE
[BUG]: Could not resolve dependencies on npm install

### ISSUE THREAD

**Issue by RaphBlanchet** [thecodingmachine/react-native-boilerplate#272]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

When using the react-native initialization command line tool provided by your Installation Guide, the command fails to run `npm install` due to unresolved dependencies related to `eslint`

### Steps to reproduce 

1. Run `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`
2. Press `N` when prompted for Typescript

### Console log

```
                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
✔ 📘 Using typescript ? (y/N) 

 … no


TheCodingMachine React-Native Boilerplate initialized with success ! 🚀

- 📚 If you need to read more about this boilerplate : https://thecodingmachine.github.io/react-native-boilerplate/
- 🤕 If you have some troubles : https://github.com/thecodingmachine/react-native-boilerplate/issues
- ⭐ If you love this boilerplate, give us a star, you will be a ray of sunshine in our lives :) https://github.com/thecodingmachine/react-native-boilerplate
✔ Executing post init script 
✖ Installing dependencies
error Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: eslint-plugin-jest@24.3.5
npm ERR! Found: @typescript-eslint/eslint-plugin@3.10.1
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   @typescript-eslint/eslint-plugin@"^3.1.0" from @react-native-community/eslint-config@2.0.0
npm ERR!   node_modules/@react-native-community/eslint-config
npm ERR!     dev @react-native-community/eslint-config@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.3.5
npm ERR! node_modules/eslint-plugin-jest
npm ERR!   dev eslint-plugin-jest@"^24.3.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @typescript-eslint/eslint-plugin@5.12.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.3.5
npm ERR!   node_modules/eslint-plugin-jest
npm ERR!     dev eslint-plugin-jest@"^24.3.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See .npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2022-02-16T23_36_09_416Z-debug-0.log
```

### Version

Latest (3.2.4)

### On which OS this issue appear on?

- [ ] IOS
- [ ] Android

### Desktop OS

MacBook Pro M1, Monterey 12.0.1

**Comment by JeremyDolle** [comment]
If you try to npm install manually is it working ?

**Comment by RaphBlanchet** [comment]
Unfortunately, no.

**Comment by JeremyDolle** [comment]
Please share me your `package.json` file and did you try to remove the `node_modules` and `package-lock.json` and run again a `npm install` cmd

**Comment by RaphBlanchet** [comment]
Here is my `package.json` file. However, as this is a problem that occurs on a fresh clone of your boilerplate, I have no `node_modules` nor `package-lock.json` file.

[package.json.txt](https://github.com/thecodingmachine/react-native-boilerplate/files/8089151/package.json.txt)

**Comment by JeremyDolle** [comment]
what is your version of npm ? did you try with yarn ?

**Comment by RaphBlanchet** [comment]
My version of `npm` is `8.3.1`

Just tried with `yarn` and it seems to work. Here is the result of `yarn.lock` : [yarn.lock](https://github.com/thecodingmachine/react-native-boilerplate/files/8089301/yarn.lock.txt)

On a side note : I originally installed NodeJs using `asdf` : https://github.com/asdf-vm/asdf-nodejs

**Comment by vetin4ri** [comment]
Unfortunatelly it's not an environment-specific issue. I have just installed the boilerplate following the tutorial and by the chance, I am doing it on a brand new Mac, so I had to install everything from scratch (homebrew, npm, literally everything) on a newest version of OS. 

The same error occured:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-plugin-jest@24.3.5
npm ERR! Found: @typescript-eslint/eslint-plugin@3.10.1
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   @typescript-eslint/eslint-plugin@"^3.1.0" from @react-native-community/eslint-config@2.0.0
npm ERR!   node_modules/@react-native-community/eslint-config
npm ERR!     dev @react-native-community/eslint-config@"^2.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.3.5
npm ERR! node_modules/eslint-plugin-jest
npm ERR!   dev eslint-plugin-jest@"^24.3.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @typescript-eslint/eslint-plugin@5.12.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   peerOptional @typescript-eslint/eslint-plugin@">= 4" from eslint-plugin-jest@24.3.5
npm ERR!   node_modules/eslint-plugin-jest
npm ERR!     dev eslint-plugin-jest@"^24.3.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/adko/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adko/.npm/_logs/2022-02-19T18_32_43_906Z-debug-0.log
```

So this is really unlikely to be coincidence. 

```
➜  myApp npm -v
8.4.1
➜  myApp node -v
v17.5.0
```

**Comment by JeremyDolle** [comment]
@vetin4ri is it failing only with npm too ?

**Comment by vetin4ri** [comment]
@JeremyDolle  Yes

**Comment by JeremyDolle** [comment]
Ok I will investigate why `eslint-plugin-jest` fail with npm and not yarn... Let me know if you find something too

**Comment by mlopezfernandez** [comment]
I have the same problem with `eslint-plugin-jest` using node v16.14.0 and npm v8.3.1.  On the other hand, I have tried with node v14.18.1 and npm v6.14.15 and everything has gone well.

**Comment by vetin4ri** [comment]
@JeremyDolle From the workaround that I used it seems like npm has either more strict, or just different dependencies version check than yarn.

**Comment by an0o0nym** [comment]
I'm having the exact same issue. npm 8.5.0 node v16.14.2.

**Comment by almafazi** [comment]
same issue

**Comment by Tespie** [comment]
I'm still facing this  issue  and using below versions 

```
C:\Projects\RN>react-native -v
9.1.1

C:\Projects\RN>node -v
v16.17.0

C:\Projects\RN>

```
