### ISSUE TITLE
THANK YOU - what a great template project

### ISSUE THREAD

**Issue by crobinson42** [thecodingmachine/react-native-boilerplate#276]
### Is your feature request related to a problem?

Thank you for your efforts and time on this template project! It is very well crafted and most importantly SIMPLE.

### Describe the solution you'd like

Keep it up - I would say to not bake in too much opinionated logic.

**Comment by JeremyDolle** [comment]
Thank a lot @crobinson42 ! 
That's a really motivating issue 💪

**Comment by quentingirard** [comment]
Yeah thank you for this template 😄. Keep it up !

We're using it on an open source medical project.

If anyone is interested in seeing the implementation → https://github.com/Wavemind/liwi-medal-reader (old version without redux-rtk)

**Comment by Angelk90** [comment]
@quentingirard : How come you didn't switch to the new version with redux-rtk?

**Comment by quentingirard** [comment]
Not enough time to migrate :(
