### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: MMKV

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#279]
### Is your feature request related to a problem?

Instead of using `@react-native-async-storage/async-storage` why not use`react-native-mmkv`?

### Describe the solution you'd like

Link: [react-native-mmkv](https://github.com/mrousavy/react-native-mmkv)

**Comment by Angelk90** [comment]
@JeremyDolle : is there any news?

**Comment by JeremyDolle** [comment]
We have to wait the new version of the cli

**Comment by JeremyDolle** [comment]
Not enough time for the moment

**Comment by Angelk90** [comment]
@JeremyDolle : is there any news?
