### ISSUE TITLE
API call URL is not working

### ISSUE THREAD

**Issue by kosijer** [thecodingmachine/react-native-boilerplate#28]
It seems that Yahoo's link is not working anymore. I'm getting "There was an error fetching the temperature" message in my app.

**Comment by arnoldc** [comment]
it is already shut down
https://piunikaweb.com/2019/01/07/query-yahooapis-com-and-weather-yahooapis-com-not-working-heres-why/

**Comment by Zilliq11** [comment]
Hello @kosijer and @arnoldc !

Thanks for your feedback !

As you said, Yahoo APIs are down. We will soon propose another API call example.

I will ping you with the PR when it's ready. 😉

**Comment by Zilliq11** [comment]
Hello @kosijer and @arnoldc !

You can check the PR #29 with a new API call example.

I close the issue. thanks again for the issue.
