### ISSUE TITLE
Use createApi reducerPath and reducer

### ISSUE THREAD

**Issue by ste7en** [thecodingmachine/react-native-boilerplate#286]
In /src/Store/index.js you define as reducers object all the api slices defined in modules directory, but why do you do this if every endpoint injected to api.js share the same reducerPath?

Wouldn't be better to add explicitly something like:
```ts
{ ...
  theme,
  [api.reducerPath]: api.reducer
}
```

**Comment by JeremyDolle** [comment]
I think you are absolutely right. I will update packages this week and the next week so I am going to use it to test your proposition and update this if it's work (It should!!) 

Thanks a lot for this !

**Comment by ste7en** [comment]
Thank you too 😉
