### ISSUE TITLE
[BUG]: Error: Unable to resolve module ../Config from /src/Services/api.js: 

### ISSUE THREAD

**Issue by Manodiestra** [thecodingmachine/react-native-boilerplate#293]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

With a fresh project created with `npx react-native init mealio_react_native_alpha --template @thecodingmachine/react-native-boilerplate`

Running Android build fails on the first attempt, then succeeds on the second attempt. The build error is this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > java.lang.OutOfMemoryError (no error message)
```
But I have about 6 GB of free memory when I run the build.

On the second attempt to run Android, I get the following error in the metro server:

```
error: Error: Unable to resolve module ../Config from /home/mano/Software/mealio_react_native_alpha/src/Services/api.js: 

None of these files exist:
  * src/Config(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * src/Config/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import { Config } from '@/Config'
  2 | import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'
  3 |
  4 | const baseQuery = fetchBaseQuery({ baseUrl: Config.API_URL })
    at ModuleResolver.resolveDependency (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/home/mano/Software/mealio_react_native_alpha/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
```

OS Ubuntu 20.04 Linux
Running app on device Pixel 4 with Android SDK API 30
Java version: openjdk 13.0.7 2021-04-20
Node version: v16.14.0
npm version: 8.7.0

### Version

3.4.3

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

Linux

**Comment by Manodiestra** [comment]
Update:
I followed the same steps as stated in the issue description and got all of the same behavior and errors on the following system:

MacOS Monterey
Java openjDK 11.0.15
node 12.18.4
npm 6.14.13
Deploying to physical Android Pixel 2 XL.

**Comment by JeremyDolle** [comment]
Sorry for the bug. I introduce it today. I will fix it as quickly as possible.
The fix is to cp the index.example.ts (or index.example.ts) into a index.ts (or index.js) file ! Tell me if it's resolved

**Comment by Manodiestra** [comment]
That fixed it. Makes sense with the missing index.js file in the directory, too. Thanks for the quick response. And thanks for the awesome boilerplate. This project definitely gets a start from me.

Mine is a index.js, by the way.

**Comment by Praveer-grover** [comment]
Hi @Manodiestra ,
You fixed this issue by renaming index.example.js to index.js right?
After doing the same I see the error in #294 .
Could you please confirm if you only did renaming or something else as well?
Thanks!

**Comment by Manodiestra** [comment]
Yeah, the import statement to @/Config won't work unless there is an index.js file that exposes the resources.

**Comment by Manodiestra** [comment]
It's worth noting, I used .js not .ts. I'm not using TypeScript.
