### ISSUE TITLE
[BUG]: Error: Unable to resolve module ./index from C:\work\projects\react-native-boilerplate\MyApp/.:

### ISSUE THREAD

**Issue by Praveer-grover** [thecodingmachine/react-native-boilerplate#294]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Was facing an issue with index.example.ts in ./Config, after checking the closed bug. I renamed it to index.ts
But now, facing the following exception on running the app in device:

Error: Unable to resolve module ./index from C:\work\projects\react-native-boilerplate\MyApp/.:

None of these files exist:
  * index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * index\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\node-haste\DependencyGraph.js:288:43)
    at C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\lib\transformHelpers.js:129:24
    at Server._resolveRelativePath (C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\Server.js:1072:12)
    at async Server.requestProcessor [as _processBundleRequest] (C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\Server.js:428:37)
    at async Server._processRequest (C:\work\projects\react-native-boilerplate\MyApp\node_modules\metro\src\Server.js:380:9)

### Version

latest, ran cmd "npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate" to install

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

windows

**Comment by JeremyDolle** [comment]
Sorry for this bug. BTW it was already reported on the issue #293. I will fix it after my vacations. 
Sorry again and enjoy the boilerplate 😊

**Comment by Praveer-grover** [comment]
@JeremyDolle Thank you for your reply, but the error in this issue is different. Initially, it was same as #293  but now after fixing it as mentioned in that issue. I see the above error now.

**Comment by Praveer-grover** [comment]
An update, I tried without typescript and it works fine. But, its still an issue with Typescript turned on.
Thanks and enjoy your vacation 😊

**Comment by JeremyDolle** [comment]
Oups sorry I do not read correctly. 

Can you make a `yarn type-check` and see if typescript can help you on the import resolution.

**Comment by Praveer-grover** [comment]
@JeremyDolle , I found the fix for it. It seems the root index.ts (which initializes the App) is missing from the Typescript version of the boilerplate, when I copied index.js from the javascript version to the typescript one. It worked fine.

**Comment by JeremyDolle** [comment]
Ok nice thanks! I will fix it as soon as possible

**Comment by JeremyDolle** [comment]
Fixed in the last version thanks for the report 😄
