### ISSUE TITLE
Using redux persist hooks with a class component

### ISSUE THREAD

**Issue by jprado** [thecodingmachine/react-native-boilerplate#301]
### Is your feature request related to a problem?

I'm trying to bring in a class based component and it makes it really hard to wire in all the redux hooks because class based components don't support hooks. 

### Describe the solution you'd like

Can you provide an example based on a class component? One that uses the redux persist store used in this template?

**Comment by JeremyDolle** [comment]
Hi @jprado 👋 
Did you look at the documentation about that in the redux toolkit: https://redux-toolkit.js.org/rtk-query/usage/examples#react-class-components ?

**Comment by jprado** [comment]
Thanks for that link! I was able to get it working. Using mapStateToProps with connect() did it.
