### ISSUE TITLE
[BUG]: npx init downloading the old template ( 3.3.0 ) instead of new one

### ISSUE THREAD

**Issue by sagarkhanal07** [thecodingmachine/react-native-boilerplate#319]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

It seems while creating the project using "_npx react-native init_" for this template, it is still using the old version.
It will be great if we can use the latest one.

### Version

3.3.0

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

Mac OS

**Comment by JeremyDolle** [comment]
Hello, yes I encountered the same issue. Even if I haven't the cli installed globally I have the issue. Maybe a solution is to run 
```
npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate 
```

It will force the installation of the new react native cli which will download the right version of the boilerplate.

Let me know

**Comment by sagarkhanal07** [comment]
Hey, thanks for the quick response. But the issue still exists.

**Comment by JeremyDolle** [comment]
Ok I will check that as soon as possible

**Comment by sagarkhanal07** [comment]
Hey !!  It is working normally for JS version.  It seems @thecodingmachine/rnb-plugin-typescript is using old version for conversion to typescript. It might work normally after you upgrade this as well.

**Comment by ha-family** [comment]
> 

still not working, i check package.json after project created, still got 3.3.0 boilerplate

{
  "name": "boilerplate",
  "version": "3.3.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "type-check": "tsc"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.3",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@reduxjs/toolkit": "^1.8.1",
    "i18next": "^21.6.16",
    "prop-types": "^15.8.1",
    "react": "17.0.2",
    "react-i18next": "^11.16.7",
    "react-native": "0.67.4",
    "react-native-flipper": "^0.143.0",
    "react-native-gesture-handler": "^2.4.1",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.13.1",
    "react-redux": "^8.0.1",
    "redux-flipper": "^2.0.1",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^3.0.1",
    "@types/fbemitter": "^2.0.32",
    "@types/jest": "^29.0.0",
    "@types/react": "^18.0.8",
    "@types/react-native": "^0.69.6",
    "@types/react-redux": "^7.1.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^7.32.0",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jest": "^24.3.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "prettier": "^2.6.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.8.2"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "moduleNameMapper": {
      ".+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$": "identity-obj-proxy"
    },
    "setupFiles": [
      "./jest.setup.js"
    ],
    "timers": "fake",
    "testEnvironment": "jsdom",
    "transformIgnorePatterns": [
      "/node_modules/(?!@react-native|react-native)"
    ]
  }
}

**Comment by ha-family** [comment]
> Hello, yes I encountered the same issue. Even if I haven't the cli installed globally I have the issue. Maybe a solution is to run
> 
> ```
> npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate 
> ```
> 
> It will force the installation of the new react native cli which will download the right version of the boilerplate.
> 
> Let me know

still not working, i check package.json after project created, still got 3.3.0 boilerplate
![111111](https://user-images.githubusercontent.com/8111587/187824375-b414a893-0058-48a8-8495-9fc6d6914ae1.jpg)

**Comment by JeremyDolle** [comment]
Ok I found the problem. I will do my best to fix it this week.

**Comment by JeremyDolle** [comment]
It should be fix
