### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: Expo integration

### ISSUE THREAD

**Issue by fredyonge** [thecodingmachine/react-native-boilerplate#323]
### Describe the solution you'd like

Hey! 

your tech stack is great and exaclty what I use. Except for one difference. I would like to use managed expo. Maybe thats something, that wouldl be interesting for you?

Thanks a lot

**Comment by JeremyDolle** [comment]
Hello @fredyonge ! 👋 
Sorry for the delay and thanks for your interest. 
For your expo request I will study how it could be integrated with this repository.

Have a nice day !

**Comment by jpainam** [comment]
Any update on this?
