### ISSUE TITLE
[BUG]: Unable to integrate Firebase

### ISSUE THREAD

**Issue by farry19** [thecodingmachine/react-native-boilerplate#325]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

I am unable to install Firebase SDK using flipper as it required use_frameworks! and when i switch my Pod file to use_framweorks, app building fails.

### Version

3.0.0

### On which OS this issue appear on?

- [X] IOS
- [x] Android

### Desktop OS

Monterey 12.6

**Comment by JeremyDolle** [comment]
Hello @farry19 ! 
I am sorry for the delay ! 

Yes it's a known issue and not a boilerplate issue. Firebase needs the `use_frameworks!` in podFile but Flipper don't work if there is this line. You have two solutions:
- Remove flipper configuration in pod file. But flipper will no works anymore...
- use firebase without `use_frameworks!`. For that, you need to replace the `use_frameworks!` line by:
```
pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
```

Hope it's help
