### ISSUE TITLE
[BUG]: Install Bundler error for typescript option.

### ISSUE THREAD

**Issue by nahcnats** [thecodingmachine/react-native-boilerplate#328]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Got this error with typescript option. Javascript option OK.
✖ Installing Bundler
error Your Ruby version is 2.7.5, but your Gemfile specified 2.7.4

### Version

Latest

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

MacOS M1 Silicon

**Comment by itsabk** [comment]
There's a ruby version mismatch in _.ruby-version_ and _Gemfile_. Just match the _Gemfile_ with the _.ruby-version_ then `cd ios` and run `pods install`
