### ISSUE TITLE
[react-i18next tyoing]: add typing to react-i18next lib

### ISSUE THREAD

**Issue by YahiaJabeur** [thecodingmachine/react-native-boilerplate#335]
### Is your feature request related to a problem?

I added this [PR](https://github.com/thecodingmachine/rnb-plugin-typescript/pull/10) while ago.
Can some one review it plz ?

### Describe the solution you'd like

I added typing to the react-i18next dependency

**Comment by JeremyDolle** [comment]
Hello,

Sorry for the delay.
First, thank you for your contribution. It was tested this Monday and it will merge soon.

FYI, I was refactoring the boilerplate right now. In react native 0.71.x the code base is in typescript so I decided to do the same. It will be easier to maintain and it's seems that more people (like us) use the typescript version. During the refactoring I include you type improvement. I will release the new version as soon as possible.

Thanks again and have a nice day

**Comment by YahiaJabeur** [comment]
Great 🎊
Thank you for the reply @JeremyDolle , looking forward to the next release!
Happy refactoring 😄
