### ISSUE TITLE
[BUG]: Lacking a default .gitignore file

### ISSUE THREAD

**Issue by aminhdev** [thecodingmachine/react-native-boilerplate#337]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

No .gitignore file in the project when init project using react-native-boilerplate@3.6.2

### Version

3.6.2

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

macOS

**Comment by JeremyDolle** [comment]
Fix in v[3.6.4](https://github.com/thecodingmachine/react-native-boilerplate/releases/tag/v3.6.4) Thanks for the report !
