### ISSUE TITLE
Unable to install project

### ISSUE THREAD

**Issue by iamharisb2** [thecodingmachine/react-native-boilerplate#338]
I am creating a new project by using "npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate" command and if I don't install my project with typescript then it gives me this error. Screenshot attached. Can anyone look into it and provide me with a solution?

![Screenshot (66)](https://user-images.githubusercontent.com/85230068/224675058-8e59ed5b-c8fc-4afb-8770-2fb9f1be6084.png)

**Comment by aum-tcm** [comment]
Indeed, `cp` do not exists in a Windows environment.

A workaround may be to use the same command in the WSL ?

**Comment by Xigma101** [comment]
If you are having this issue and have git installed, open git bash, cd to desired folder, enter "npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate" and if you are using Javascript, the issue will no longer be there. Hope this work around helps.

**Comment by JeremyDolle** [comment]
Thanks @Xigma101 ! 
Please @iamharisb2, let us know if it's working for you. It could be a part of a "troubleshooting section"

**Comment by tahaAlgoace** [comment]
this issue is not resolve yet I am facing this issue on mac in bash or zsh terminal also

**Comment by tahaAlgoace** [comment]
@JeremyDolle this issue is not resolve yet I am facing this issue on mac in bash or zsh terminal also


![Screenshot 2023-06-02 at 1 22 45 PM](https://github.com/thecodingmachine/react-native-boilerplate/assets/121221340/b0d44d18-e9f6-4cd6-b17c-552d4bc56f89)

**Comment by mtalhagaoglu** [comment]
Do we have any solution for this problem? I also have this issue on my machine.

**Comment by JeremyDolle** [comment]
Of course I have a quick fix solution. We use yarn in our script. Install it globally and It will work.
I will fix by adding a flag for using npm or yarn but for now you will need to install yarn
