### ISSUE TITLE
[BUG]: Project Initialization stuck at "Executing post init script"

### ISSUE THREAD

**Issue by salman-kryptomind** [thecodingmachine/react-native-boilerplate#343]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Simply ran the command 
```npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate```
Ever since it is stuck on **Executing post init script **
<img width="247" alt="Screenshot 2023-03-18 at 2 48 41 AM" src="https://user-images.githubusercontent.com/80668339/226059291-3fd6812c-bced-4aa3-bfec-758e9d4236fb.png">

My Internet connection is fine with a good bandwidth.

Node version: 16.14.2
Npm : 8.5.0

### Version

3.6.5

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

MacOS ( Ventura)

**Comment by salmandayal** [comment]
Facing the same issue. +1

**Comment by JeremyDolle** [comment]
I cannot reproduce it on my side. Can you try again ?

**Comment by DaniyalAhmerKryptoMind** [comment]
Facing the Same Issue, taking too long on "Executing post init Script".

**Comment by lakhvirk** [comment]
I had the same issue, I believe it supposes to ask for typescript yes or no but nothing shows up.
I press enter when I see this option and good to go 🚀 . TCM guys should fix this up.

**Comment by JeremyDolle** [comment]
Ah ok I see ! It's probably an issue with the version of your cli (installed globally or in your cache). The step "Executing post init script" now not have a loader but a ℹ as prefix.

Let's try to run `npx react-native@next init MyApp --template @thecodingmachine/react-native-boilerplate` to be sure to have the last one
