### ISSUE TITLE
[BUG]: Duplicate Podfile

### ISSUE THREAD

**Issue by hungfhp** [thecodingmachine/react-native-boilerplate#344]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

When i init project with this template.
It occur an error:

error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. 

![Screenshot 2023-03-22 at 14 17 34](https://user-images.githubusercontent.com/18446429/226808650-f7c0c2df-ded9-4e3d-8fe2-4d5d35beae09.png)

### Version

3.6.5

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

Mac OS Ventuna 13.2

**Comment by JeremyDolle** [comment]
Yes I know, the same appear to me and I found this issue : https://github.com/facebook/react-native/issues/35801. I will investigate if it's caused by our template or the cli. Let me know if you find a solution in the previous link

**Comment by farry19** [comment]
<img width="1438" alt="Screenshot 2023-03-24 at 6 54 12 AM" src="https://user-images.githubusercontent.com/1573511/227404461-be034cb2-6bf0-4592-83c6-be866cecae8c.png">

I am facing the same issue.

**Comment by mkabatek** [comment]
I'm having the same issue. Using the following thread: https://github.com/facebook/react-native/issues/35801 

I did these steps.

1. navigate to your app folder
2. cd ios
3. bundle install (you need to run this only once)
4. bundle exec pod install

This give the following error.

```
[!] CocoaPods could not find compatible versions for pod "hermes-engine":
  In snapshot (Podfile.lock):
    hermes-engine (from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`)

  In Podfile:
    hermes-engine (from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`)

It seems like you've changed the version of the dependency `hermes-engine` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update hermes-engine --no-repo-update` to apply changes made locally.
```

Then I ran `pod update hermes-engine --no-repo-update` as suggested. Then I could run the project via xcode.
