### ISSUE TITLE
[BUG]: Error: EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by ionwebs** [thecodingmachine/react-native-boilerplate#349]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat '*\node_modules\react-native-reanimated\android\build\intermediates\cxx\Debug\543f3x24\obj\x86\libreanimated.so.tmpea04be6'
Emitted 'error' event on NodeWatcher instance at:
    at *\node_modules\metro-file-map\src\watchers\NodeWatcher.js:235:14
    at FSReqCallback.oncomplete (node:fs:208:21) {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: '*\\node_modules\\react-native-reanimated\\android\\build\\intermediates\\cxx\\Debug\\543f3x24\\obj\\x86\\libreanimated.so.tmpea04be6'
}

Node.js v18.15.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Version

0.68

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

windows 11

**Comment by victor20m** [comment]
Try running the console (or vscode if you're using it) as admin.

**Comment by arcelluceno11** [comment]
> Try running the console (or vscode if you're using it) as admin.

Still doesn't work...

**Comment by kangfredy** [comment]
hi it has issue with latest react native 0.71.4 you can downgrade your react version to stable version 
https://www.npmjs.com/package/react-native?activeTab=versions

or if you are using windows try using this and put this command on bat file
`react-native run-android & react-native start --reset-cache`
