### ISSUE TITLE
Clean boilerplate 50% error rate

### ISSUE THREAD

**Issue by perqa** [thecodingmachine/react-native-boilerplate#35]
Just got the boilerplate up-and-running. Clicking refresh results in error message 50% of attempts. I assume this is not intended? What could be wrong?
<img width="333" alt="Screen Shot 2019-03-14 at 16 43 57" src="https://user-images.githubusercontent.com/960796/54370972-e09e4780-4678-11e9-8342-19ecae545edd.png">

MacOS Sierra 10.12.6 (16G1815)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Started app by running  >react-native run-ios

**Comment by AurelGit** [comment]
Hello @perqa !

Thanks for your feedback.

In fact, it's absolutely intended ! As you can see on this line : https://github.com/thecodingmachine/react-native-boilerplate/blob/5902e6b1ac592da5f60f862893d830a2e693bd36/App/Services/UserService.js#L23

```javascript
 // Simulate an error 50% of the time just for testing purposes
  if (Math.random() > 0.5) {
    return new Promise(function(resolve, reject) {
      resolve(null)
    })
  }
```

It's just to provide a random error to explain how to manage it.
If an error appends, you can display a different message or something else.

See you on the boilerplate, and don't hesitate to tell us if you have some questions or remarks !

**Comment by perqa** [comment]
Haha, sorry about that! :-) Thanks for a quick response, and thanks for sharing the boilerplate!
