### ISSUE TITLE
Error: Command failed: cp -R src/theme/assets js/src/theme/assets

### ISSUE THREAD

**Issue by RaguRam1991** [thecodingmachine/react-native-boilerplate#351]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

'cp' is not recognized as an internal or external command,
operable program or batch file.

suggested solution for windows 

#copy assets directory
-cmd copy \y assets bin\js\

### Version

3.6.5

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

windows

**Comment by JeremyDolle** [comment]
Can you try to run the init command in git bash ?

**Comment by RaguRam1991** [comment]
> Can you try to run the init command in git bash ?

seems working, thank you.
