### ISSUE TITLE
[BUG]: App is not running

### ISSUE THREAD

**Issue by Shankar006-ss** [thecodingmachine/react-native-boilerplate#353]
### react-native environment setup

- [ ] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Whenever i try to create a new app using codingMachine boiler plate the app is not running on Android

![image](https://user-images.githubusercontent.com/113160165/235063033-b5aab338-b619-48aa-9868-c408e8001d42.png)

Steps to reproduce the error:

1. Create an react native project using  npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate
2.  Install Node modules using 'npm install'
3.  Open android in android studio and then run project.

### Version

Latest version

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

windows 11

**Comment by JeremyDolle** [comment]
When you said :
> Open android in android studio and then run project.

run not running android with `yarn android` command ?
