### ISSUE TITLE
[BUG]: An error occurred while Installation

### ISSUE THREAD

**Issue by Hyg900928** [thecodingmachine/react-native-boilerplate#357]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/19190553/d38a05c5-1d07-43bf-8f59-84c0db2370b1)

An error occurred during the install, what is the reason?

### Version

3.6.5

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

macOs 12.2.1

**Comment by Hyg900928** [comment]
![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/19190553/e017e4c9-6001-4cad-83ce-647e77656488)

**Comment by Hyg900928** [comment]
Does anyone know what is the reason for this?

**Comment by GeoffreyOlivier** [comment]
same error.

**Comment by JeremyDolle** [comment]
Duplicate of [#344](https://github.com/thecodingmachine/react-native-boilerplate/issues/344)

**Comment by truongnat** [comment]
you can change version ruby to 2.7.7
