### ISSUE TITLE
[BUG]:   i have problem on samsung android, no response when pressing textinput or navigation

### ISSUE THREAD

**Issue by vnphu** [thecodingmachine/react-native-boilerplate#367]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

when i build or release on samsung device, it doesn't react when i press button or textinput

### Version

3.7.o

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

12

**Comment by FBL-dev** [comment]
I have exactly the same problem, I have to click a dozen times on the buttons for the click to work.

**Comment by JeremyDolle** [comment]
Maybe there is an asset on top of it and the touch does not pass through so the button is not triggered. Could you try to remove each asset and see if one of them block the access to the button ?

**Comment by vnphu** [comment]
> Maybe there is an asset on top of it and the touch does not pass through so the button is not triggered. Could you try to remove each asset and see if one of them block the access to the button ?

Is it possible that the reason is due to the new architecture of react native, assets or the whole src, I use react native 0.71 version, it's normal

**Comment by JeremyDolle** [comment]
Yes it's possible. I am on vacation for now, so I cannot make tests.

Did you have the issue on the default screen (Example.tsx) of the boilerplate or any of your screens.

If it's on the Example screens could you try to remove all `<Image />` and see if you have access to buttons.

Did the error appears only on Samsung? Did you try another device ? Which one ?

Let me know 🙂

**Comment by vnphu** [comment]
it started crashing when I used navigation to switch screen, 
Besides samsung, google pixel 5 also suffers

**Comment by JeremyDolle** [comment]
Can you share me a reproductible example ? I cannot reproduce on my side

**Comment by rdmb11** [comment]
@JeremyDolle hello, i have the same issue, check video please

https://github.com/thecodingmachine/react-native-boilerplate/assets/75898310/f0893827-2f0e-407f-a192-8ef59fc5eff6

Android 12
