### ISSUE TITLE
[BUG]:  Issue with android build getting error as "[CXX1428] exception while building Json A problem occurred starting process"

### ISSUE THREAD

**Issue by ghulamyazdani** [thecodingmachine/react-native-boilerplate#371]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

ss for the issue

<img width="760" alt="image" src="https://github.com/thecodingmachine/react-native-boilerplate/assets/55938346/ac5245fb-94fa-49b5-9018-8fb9a4e8b797">

### Version

Newest

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

macOs

**Comment by JeremyDolle** [comment]
It's seems to be a react-native issue, not related to this boilerplate: https://github.com/facebook/react-native/issues/34871

Hope it's help
