### ISSUE TITLE
[BUG]: Post init script Error starting new project

### ISSUE THREAD

**Issue by digimatt22** [thecodingmachine/react-native-boilerplate#372]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

After running npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate the following error is reported:

🧱 Building the javascript source...
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: npx tsc --jsx react-native --module ESNext -t esnext --outDir js --noEmit false
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at /private/var/folders/ld/hrw7ryqs1gx_tg51d0l83r400000gn/T/rncli-init-template-S7Y4r1/node_modules/@thecodingmachine/react-native-boilerplate/template/plugins/compile-js/plugin.js:13:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Version

Latest

### On which OS this issue appear on?

- [ ] IOS
- [ ] Android

### Desktop OS

OSX Ventura 13.4.1 (c)

**Comment by grantspilsbury** [comment]
I get the same error

**Comment by Jarvie789** [comment]
same error

**Comment by JeremyDolle** [comment]
Can you try running `npx tsc --jsx react-native --module ESNext -t esnext --outDir js --noEmit false` out of the script and give me the results.
Please also provide me the node, npm and yarn version of your device.
