### ISSUE TITLE
[BUG]: Application not running on Windows

### ISSUE THREAD

**Issue by mrsaadabbasi** [thecodingmachine/react-native-boilerplate#373]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

The Application is not running on Windows OS, we have tried around 6 different Windows OS machines with windows 10 and 11. We are facing same permission issues
 
![issue](https://github.com/thecodingmachine/react-native-boilerplate/assets/5177662/c6110afe-f1bd-4bb0-8290-1e2add2e4ac8)

### Version

3.7.0

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

Windows

**Comment by JeremyDolle** [comment]
Can you provide the steps please ? When did this appear? At the initialization ? After choosing typescript? JavaScript? After running yarn android ? Yarn start ?

Let me know

**Comment by Akozyrev222** [comment]
> Can you provide the steps please ? When did this appear? At the initialization ? After choosing typescript? JavaScript? After running yarn android ? Yarn start ?
> 
> Let me know

same issue, after running yarn android

**Comment by Akozyrev222** [comment]
I had same problem, try to change project directory from system disk, I think that windows blocked some cmake scripts, when its try to start inside C: disk
its works for me
