### ISSUE TITLE
[BUG]: New application set up from template won't start

### ISSUE THREAD

**Issue by OultimoCoder** [thecodingmachine/react-native-boilerplate#374]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

I followed the react native setup tutorial from the website and I installed this project as per the instructions. I have tried with a virtual environment and also my own android phone but every time no matter what I do, I get this error:

```
BUILD SUCCESSFUL in 2m
213 actionable tasks: 208 executed, 5 up-to-date
info Connecting to the development server...
info Starting the app on "RFCT80RZZ6D"...
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.langki/.MainActivity }
Error type 3
Error: Activity class {com.langki/com.langki.MainActivity} does not exist.
```

I have followed a bunch of guides and done various things like deleting the build folder, uninstalling all with gradle, wiping user data, checking package names match etc but I can't get it to work no matter what I try.

### Version

latest

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

Ubuntu 22.0.4

**Comment by OultimoCoder** [comment]
I also just deleted the folder and reinstalled from template and got the same issue

**Comment by AhmadAlz7** [comment]
Same issue here

**Comment by AhmadAlz7** [comment]
if you want a walkaround solution:
go to android > app > src > main > AndroidManifest.xml
you will find 2 activites :
`      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name"
        android:exported="true"
      >
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
        </intent-filter>
      </activity>`
      
      you need to move this part from the first activity :
      `<category android:name="android.intent.category.LAUNCHER" />`
      and put it in the same place for the second activity
      
      and then delete/comment the first activity
      your new code should look like:
      `      

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>`
