### ISSUE TITLE
[BUG]: Unable to install dependencies with Node 16

### ISSUE THREAD

**Issue by wuuJiawei** [thecodingmachine/react-native-boilerplate#378]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

```
error metro-config@0.79.0: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
error Found incompatible module.
```

Maybe the same issue like https://github.com/facebook/react-native/issues/38298

### Version

3.7.2

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

macos Ventura 13.5

**Comment by wuuJiawei** [comment]
After upgrading ReactNative to `0.72.2` and removing `@types/metro-config`, the problem is solved.

**Comment by JeremyDolle** [comment]
Hello, the solution is to upgrade your Node version instead of removing dependencies.
FYI, the current LTS version of node is 18.17.1 so you could easily upgrade it without any danger.
