### ISSUE TITLE
In Window "cp" command will not work while install [BUG]: 

### ISSUE THREAD

**Issue by 6ixline** [thecodingmachine/react-native-boilerplate#381]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

While installing using "npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate" this command I was getting was "cp is not recognized as an internal or external command" as there is no such thing as "cp" in the window.

### Version

Latest one

### Do you use TypeScript?

- [ ] Yes
- [X] No

### On which OS this issue appear on?

- [ ] IOS
- [ ] Android

### Desktop OS

Window

**Comment by JeremyDolle** [comment]
Normally, if you use git bash instead of the windows terminal it should work

**Comment by soWizardly** [comment]
Confirming @JeremyDolle 's solution worked for me on Windows 10. This may seem minor but as a someone trying to get into RN and still working towards getting my local env setup, this saved me a lot of time.
