### ISSUE TITLE
V4 

### ISSUE THREAD

**Issue by dlato97** [thecodingmachine/react-native-boilerplate#384]
Hi, first of all thanks for the powerful boilerplate.

I noticed there is a pull request for a new version. when will it be accepted? I have to start developing a new app and would like to use the latest version.

Thanks a lot

**Comment by JeremyDolle** [comment]
Hello, sorry for the delay. 
Thanks a lot for your feedback and your patience.

We are working internally on the new version to see if it's working well or not. We have found a lot of improvements to add on this v4.
So for the moment I don't know when it will be ready for releasing. 
I will let you know.

**Comment by JeremyDolle** [comment]
The V4 is now available ! thanks for your patience
