### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: Support for npm or specify yarn as prerequisite

### ISSUE THREAD

**Issue by CatalinTudose** [thecodingmachine/react-native-boilerplate#386]
### **Problem**:

While trying to set-up using template got error for yarn missing.Would be nth to have npm supported or maybe mention yarn as a prerequisite?

### **Suggestion**

Mentioning yarn as prerequisite would be highly appreciated.

### **Alternative**

Support for npm

Thank you.

**Comment by JeremyDolle** [comment]
The v4 is available, we follow the cli for the logic. Now if you have yarn it will use it, if not it will use npm. If not, an error occured
