### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: How To handle deep link in this structure

### ISSUE THREAD

**Issue by sun1211** [thecodingmachine/react-native-boilerplate#390]
### Is your feature request related to a problem?

Handle Deep link in android and ios

### Describe the solution you'd like

handle deep link in android and ios

**Comment by JeremyDolle** [comment]
Hi @sun1211,
Deeplink could be related to the navigation (doesn't matter the template). So, I think you could find all information [here](https://reactnavigation.org/docs/deep-linking/).
