### ISSUE TITLE
[BUG]: cannot run  android

### ISSUE THREAD

**Issue by wangyiwu** [thecodingmachine/react-native-boilerplate#392]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Steps to reproduce error.

Initialize the new app
npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate

Run on Android emulator
yarn android

```
w: C:\02-DATA-USER\TestCode\Application\MyApp\node_modules\react-native-safe-area-context\android\src\main\java\com\th3rdwave\safeareacontext\SafeAreaView.kt: (58, 23): 'getter for uiImplementation: UIImplementation!' is deprecated. Deprecated in Java

> Task :react-native-reanimated:configureCMakeDebug[arm64-v8a]
node:internal/process/promises:289
b8e6f29'
Emitted 'error' event on NodeWatcher instance at:
    at C:\02-DATA-USER\TestCode\Application\MyApp\node_modules\metro-file-map\src\watchers\NodeWatcher.js:231:14 {
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\02-DATA-USER\\TestCode\\Application\\MyApp\\node_modules\\react-native-reanimated\\android\\.cxx\\Debug\\583l13e6\\arm64-v8a\\CMakeFiles\\CMakeTmp\\cmTC_079ac.tmpb8e6f29'
}

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Version

3.7.2

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

Windows 11

**Comment by wangyiwu** [comment]
> Following this [issue](https://github.com/software-mansion/react-native-reanimated/issues/4712), maybe you have to upgrade your android sdk

I follow https://reactnative.dev/docs/environment-setup. Im using SDK Android SDK Platform 33

**Comment by JeremyDolle** [comment]
What is your JDK version ?

**Comment by wangyiwu** [comment]
> What is your JDK version ?

Isssue is solved by tick to "Intel x86 Atom_64 System Image" options
