### ISSUE TITLE
[BUG]: Got Type Errror at NativeWebSocketModule.connect when: Show Element Inspector => Choose Network tab 

### ISSUE THREAD

**Issue by thaibm** [thecodingmachine/react-native-boilerplate#396]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Got Type Errror at NativeWebSocketModule.connect when: Show Element Inspector => Choose tab Network

**Message details**: 

```

 Error: TypeError: Cannot assign to property 'connect' on HostObject with default setter

This error is located at:
    in NetworkOverlay (created by InspectorPanel)
    in RCTView (created by View)
    in View (created by InspectorPanel)
    in InspectorPanel (created by Inspector)
    in RCTView (created by View)
    in View (created by Inspector)
    in RCTView (created by View)
    in View (created by Inspector)
    in Inspector
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in TrudiPortal(RootComponent), js engine: hermes

```

in file: node_modules\react-native\Libraries\WebSocket\WebSocketInterceptor.js
![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/5625757/ad45b6ba-ae45-4a05-ac29-83e62aea60ad)

### Version

latest

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

Window 10

**Comment by JeremyDolle** [comment]
I will check that.

Why don't you use flipper for network inspection ?

**Comment by thaibm** [comment]
> flipper

Thank you.
