### ISSUE TITLE
[BUG]: Windows init projet

### ISSUE THREAD

**Issue by mirza-bilal-amjad** [thecodingmachine/react-native-boilerplate#397]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Once I Init that boilerplate i got that error and it is only happening in Windows not in Macs

![image](https://github.com/thecodingmachine/react-native-boilerplate/assets/69304697/28ea9683-b9af-4411-b4ee-20233eee8418)

### Version

THe lated one V4 that you have commited 6 days ago on 01-12-23

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

Windows 11

**Comment by JeremyDolle** [comment]
To fix your issue, you just have to use git bash to init your project. Git bash will allow you to use `cp` or `rm` commands which are required during setup

**Comment by JeremyDolle** [comment]
Close due to inactivity. Feel free to reopen
