### ISSUE TITLE
Add the Beta build page again

### ISSUE THREAD

**Issue by muhammadhassan149** [thecodingmachine/react-native-boilerplate#399]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

The beta build page not found.
https://thecodingmachine.github.io/react-native-boilerplate/docs/BetaBuild/

### Version

latest

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [X] IOS
- [X] Android

### Desktop OS

Mac

**Comment by JeremyDolle** [comment]
This page was removed because it was outdated. Feel free to open a PR with an up-to-date documentation about Fastlane
