### ISSUE TITLE
OS X Mojave compatibility?

### ISSUE THREAD

**Issue by mnapoli** [thecodingmachine/react-native-boilerplate#4]
https://reddit.com/r/reactnative/comments/9j0smk/a_react_native_boilerplate_focused_on_separation/e6qljfl/

> I just upgraded to Mojave and this seems to error out for me. I think the SDK version needs to be upgraded to the latest to be compatible with Mojave / Xcode 10. Just a heads up!

It might be worth trying Mojave out.

**Comment by AurelGit** [comment]
Maybe related to https://github.com/facebook/react-native/issues/19774

**Comment by JeremyDolle** [comment]
After testing it, there is no compatibility issue
