### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA][v4.0.0]: How about if there is an option for enable redux when create new project 

### ISSUE THREAD

**Issue by aminhdev** [thecodingmachine/react-native-boilerplate#401]
### Is your feature request related to a problem?

In the case we want to init project with redux setup as default state management 

### Describe the solution you'd like

When install new project will have encounter the following prompt: 
`Using redux ? (Y/n)`

**Comment by nonishant** [comment]
why redux?, we already have react-query to handle server state, just to handle app state zustand can be used?

**Comment by JeremyDolle** [comment]
You have an explanation [here](https://github.com/thecodingmachine/react-native-boilerplate/releases/tag/4.2.0). 
We always have the plan to make contributors add plugins during the boilerplate initialization.
