### ISSUE TITLE
Application is not running in android(adb).

### ISSUE THREAD

**Issue by MashoodAli-Official** [thecodingmachine/react-native-boilerplate#406]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

Hi!
I'm encountering an issue when attempting to run the React Native boilerplate (template app) on an Android virtual device (Screenshot #1). I am using version 4.0.0 of the boilerplate and React Native 0.72. I set up the React Native environment just a day ago, and everything is up-to-date with the latest prerequisite libraries and SDK on my system. Even i did not make minor change in the code but still not working . But the app works perfectly fine on iOS.

However, when I try to create and run a simple React Native project using "npx react-native@latest init AwesomeProject," it runs successfully on both iOS and Android.
. 
(_<img width="885" alt="Screenshot # 01" src="https://github.com/thecodingmachine/react-native-boilerplate/assets/54344218/8d8581e8-4c35-4920-888f-1edb3f48096e">_)
Please help me in this issue. 

### Version

4.0.0

### Do you use TypeScript?

- [ ] Yes
- [X] No

### On which OS this issue appear on?

- [ ] IOS
- [X] Android

### Desktop OS

macOS Sonoma 14.0

**Comment by MashoodAli-Official** [comment]
> Seems to be related to mmkv and reanimated dependencies. Try to reinstall them

I have reinstalled the dependencies and even removed them one by one. However, the problem persists. Even after removing one dependency, the terminal continues to show the issue with the next dependency.
<img width="898" alt="Screenshot # 02" src="https://github.com/thecodingmachine/react-native-boilerplate/assets/54344218/9e125999-7a1c-4a7d-905f-11e7b04d52a0">

As you can see in **Screenshot #02**, I have removed the MMKV, Reanimated, and Flipper dependencies. However, the terminal now displays the "something went wrong" error related to the Gesture Handler dependency.

**Comment by JeremyDolle** [comment]
What is the exact error ?

**Comment by JeremyDolle** [comment]
did you follow this kind of issue: https://github.com/mrousavy/react-native-mmkv/issues/563. maybe double check the cmake installation. cannot reproduce on my side

**Comment by JeremyDolle** [comment]
Close due to inactivity. Feel free to re-open if needed.

**Comment by MashoodAli-Official** [comment]
@JeremyDolle Hi there! 

I have fixed the problem; you can say I have found the solution. I tried running the app on both the simulator and emulator simultaneously. The app runs immediately on iOS, but when I attempt to run it on Android, it gives the same error, prompting me to delete the libraries one after another. 
To resolve this, I opened the same project in Android Studio and tried running the app. After the Gradle build, the application ran successfully. During this process, the application remained connected with VS Code as well. As you can see in the attached **screenshot**, I made a change, and it reflected on both the Android and iOS sides.
<img width="1216" alt="screenshot" src="https://github.com/thecodingmachine/react-native-boilerplate/assets/54344218/84d4913f-33dd-4728-8c02-1fb805c2a4e3">
