### ISSUE TITLE
Can you share a login code

### ISSUE THREAD

**Issue by xiaoyuchen** [thecodingmachine/react-native-boilerplate#41]
Hi there 

The project is nicely organised. I love it. Only one little request if you can post a login code, as the example is only demonstrate an api call to retrieve  the data, we need an example for post data call as well.

Thanks,
Xiaoyu Chen

**Comment by AurelGit** [comment]
Hello @xiaoyuchen !

Thanks for your kind feedback.

Please let me some time to explain you how to manage an authentication flow.
I'll post here some code example as soon as possible.

Keep in touch !

**Comment by xiaoyuchen** [comment]
Thanks @AurelGit. Looking forward a nice code.

**Comment by wasitum** [comment]
Following that thread, I'm interested as well, thanks a lot :)

**Comment by AurelGit** [comment]
Hey @xiaoyuchen and @wasitum !

I'm working on a complete documentation of an authentication workflow. 
It should be ready before the end of the week 😄

**Comment by trinadhkoya9** [comment]
Sounds good !! I

**Comment by wasitum** [comment]
Hello @AurelGit , thanks a lot for taking time for that workflow :) Any update on this by any chance ?

**Comment by AhmedMasoodSiddiqui** [comment]
great work, any update regarding this request?

**Comment by CreativeBulma** [comment]
Hi,

any news regarding the integration of authentication flow ?

regards

**Comment by AurelGit** [comment]
We are currently working on a new repository containing examples of code and other tip and tricks. 
First example will be the authentication flow.

Hope it will ready really soon guys, we do not forget you 😀

**Comment by youyi1314** [comment]
Any update about this?
If posible share some login code for api methods?
Login > Get Token > Save to State
Get User > Get token from State set to Axios header > Call getUser() api

**Comment by youyi1314** [comment]
Any update about this?
If posible share some login code for api methods?
Login > Get Token > Save to State
Get User > Get token from State set to Axios header > Call getUser() api

Best Regards

**Comment by PurwadiPw** [comment]
Any update about this?

**Comment by kr-kumar** [comment]
@AurelGit  Any update on auth?. Thanks

**Comment by Angelk90** [comment]
@AurelGit : Are there any news?

**Comment by JeremyDolle** [comment]
Hi everyone,
Sorry for the delay... we have a lot of stuff at the moment and a lot of ideas, we are working on it, it will be on another repository and we will provide not only a login screen example but some experimental and animation stuff.
See you soon 😉

**Comment by tcagkansokmen** [comment]
any update?

**Comment by JeremyDolle** [comment]
Hi, we have made a repository with a login by session exemple [here](https://github.com/thecodingmachine/react-native-workshop). This Will be refactored when the boilerplate V2 will be released but you have an exemple that can be used.
