### ISSUE TITLE
Adding a Q&A section to the documentation

### ISSUE THREAD

**Issue by alanbosco003** [thecodingmachine/react-native-boilerplate#411]
Hey there!

I'm relatively new to React Native and stumbled upon your awesome boilerplate template. Firstly, thanks a ton for putting it together!

I was wondering if there's a way to integrate a feature where users can ask questions directly within the documentation. As a beginner, having a platform to ask questions and get help from fellow developers would be incredibly beneficial.

However, I'm not entirely sure about the feasibility of implementing such a feature. If it's something that can be done, I'm more than willing to contribute and work on it.

Looking forward to hearing your thoughts on this!

Cheers!

### Describe the solution you'd like

Can we add a Q&A section to the documentation?

-> where the users can ask their doubts.
-> which will attract new developers and find it reliable.

**Comment by JeremyDolle** [comment]
Hello @alanbosco003, thanks for your feedback ! We appreciate it a lot.

What kind of question do you think about ? If you have example, can you share it ?

if it's common asked questions, we can add a Q&A in the documentation. If it's more discussions about the boilerplate, maybe we can think about the GitHub discussion tab but it's a lot of time to organise and manage.
