### ISSUE TITLE
Rewrite with Hooks

### ISSUE THREAD

**Issue by ozanmanav** [thecodingmachine/react-native-boilerplate#42]
Hi guys,

Do you think rewrite this boilerplate with hooks ? :) I think it can extreme perfect.

If you start this boilerplate our developers can attend the develop this boilerplate.

Thanks,
Ozan.

**Comment by AurelGit** [comment]
Hello @ozanmanav !

It's absolutely in our todo list. 

We are searching for the best approach of implementation, trying to keep this boilerplate as simple as possible.

It would be a pleasure if you want to help us. Feel free to open a PR :)

See you soon with hooks !

**Comment by kbaxx** [comment]
any update on this?

**Comment by JeremyDolle** [comment]
Hi @kbaxx, @ozanmanav.

A [Pull request](https://github.com/thecodingmachine/react-native-boilerplate/pull/105) is now open. It will be merged soon but if you want to take a look 😉

**Comment by AurelGit** [comment]
See #105 😄
