### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: add support for several font families

### ISSUE THREAD

**Issue by M21H** [thecodingmachine/react-native-boilerplate#428]
### Is your feature request related to a problem?

display several font families in the app

### Describe the solution you'd like

add font families to _config

**Comment by JeremyDolle** [comment]
as the theme configuration is not hidden code, you always can add configuration or static style.

ex:
```
export const staticFontStyles = {
  // ...
  brandFontFamily: {
    fontFamily: 'MyAwsomeFont',
  },
  // ...
} as const satisfies Record<string, TextStyle>;
```
