### ISSUE TITLE
[NEW FEATURE REQUEST/IDEA]: add suppot system theme

### ISSUE THREAD

**Issue by M21H** [thecodingmachine/react-native-boilerplate#429]
### Is your feature request related to a problem?

users want to use the same theme as on their device

### Describe the solution you'd like

add system theme (dark/light)

**Comment by JeremyDolle** [comment]
You can already do it in fact.

you can get the device colorScheme by using the Apparence API provided by react-antive: https://reactnative.dev/docs/appearance

So, with a little modification in ThemeProvider:
```
...
        // Initialize theme at default if not defined
	useEffect(() => {
		// get device scheme dark or light
		const deviceScheme = Appearance.getColorScheme();
		if (deviceScheme === 'dark') {
			storage.set('theme', 'dark');
			setVariant('dark');
		} else {
			storage.set('theme', 'default');
			setVariant('default');
		}
	}, []);
...
```

you can acheve it
