### ISSUE TITLE
[TYPO]: border radius styles generator

### ISSUE THREAD

**Issue by PurwadiPw** [thecodingmachine/react-native-boilerplate#430]
https://github.com/thecodingmachine/react-native-boilerplate/blob/65850e1e1405af978c92db4b9fe91fb9d3be199b/template/src/theme/borders.ts#L45

There is a little typo in the border radius styles generator. 🙏

**Comment by JeremyDolle** [comment]
Hello, the fix is in the new version! Thanks for the report
