### ISSUE TITLE
Publish an example on snack.expo.io

### ISSUE THREAD

**Issue by Angelk90** [thecodingmachine/react-native-boilerplate#54]
Hi @thecodingmachine, @AurelGit :
Would it be possible to publish the code on snack.expo.io, so as to be able to test it without having to create a project on your PC?

**Comment by AurelGit** [comment]
Hello @Angelk90 

It doesn't seems possible to use snack.expo.io because the boilerplate is built in an ejected mode.

Thanks for your feedback !
