### ISSUE TITLE
Execute the react-native run-android command app flashback according to the document pull template

### ISSUE THREAD

**Issue by liuyunzyj** [thecodingmachine/react-native-boilerplate#62]
![image](https://user-images.githubusercontent.com/40293335/61282213-84e1f780-a7ed-11e9-9c50-2690e3ff2426.png)

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/61282298-ad69f180-a7ed-11e9-9d21-eb3a971a24f5.png)

**Comment by liuyunzyj** [comment]
According to the document configuration to this step, I tried to use the react-native run-android, but found that the app would flash back, may I ask what's the reason, or my configuration is wrong, and I still lack of configuration steps

**Comment by AurelGit** [comment]
Hello @liuyunzyj !

Do you have any error message in the metro bundler or the application ?

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/61284412-7c8bbb80-a7f1-11e9-858f-976c5118d8f3.png)
It turns out that's the problem,the new version is still the problem

**Comment by liuyunzyj** [comment]
![image](https://user-images.githubusercontent.com/40293335/61284532-bb217600-a7f1-11e9-8c28-0b82fbc25efe.png)

**Comment by liuyunzyj** [comment]
This error occurs when I use this command yarn run rename

**Comment by AurelGit** [comment]
Does the `/android/app/src/main/java/com/[yourprojectname]/MainActivity.java` file disappeared ?

In this case, please try to create it manually (using the one in the boilerplate).

You can look at [this comment](https://github.com/thecodingmachine/react-native-boilerplate/issues/34#issuecomment-503129849) too

We will try to use another method to rename the application.

**Comment by liuyunzyj** [comment]
Ok, thank you

**Comment by liuyunzyj** [comment]
@AurelGit 
![image](https://user-images.githubusercontent.com/40293335/61363623-ec17ae80-a8b6-11e9-80e7-9d9735b0d895.png)
Is it too much code for each service to write

**Comment by liuyunzyj** [comment]
Can you provide to embed the project template under the encapsulation of axios request

**Comment by AurelGit** [comment]
@liuyunzyj take a look at #74 ;)
