### ISSUE TITLE
running on ios giving the following error with checked out base code

### ISSUE THREAD

**Issue by gajen0981** [thecodingmachine/react-native-boilerplate#63]
error: bundling failed: Error: While resolving module `App/Config`, the Haste package `App` was found. However the module `Config` could not be found within the package. Indeed, none of these files exist:

![Simulator Screen Shot - iPhone X - 2019-07-18 at 16 29 49](https://user-images.githubusercontent.com/980887/61489753-67da2f80-a979-11e9-8297-d2c626da1818.png)

**Comment by AurelGit** [comment]
Hello!

You should create the index.js file inside the Config as specified in the Readme.

See you!
