### ISSUE TITLE
Release info or tags

### ISSUE THREAD

**Issue by MaxiSantos** [thecodingmachine/react-native-boilerplate#65]
Can you please use the release github tab? That way we would know what are the new features you are adding here in this feature over time. Or maybe add some tags for the releases

**Describe alternatives you've considered**
We are using this boilerplate for react-web and it's good: [https://github.com/react-boilerplate/react-boilerplate/releases](https://github.com/react-boilerplate/react-boilerplate/releases)

Thanks

**Comment by AurelGit** [comment]
Let's do it 🚀 
Thanks for the suggestion @MaxiSantos !
