### ISSUE TITLE
eslint parser

### ISSUE THREAD

**Issue by antoinerousseau** [thecodingmachine/react-native-boilerplate#66]
The eslint config proposed in the boilerplate does not support some features like arrow functions class methods, e.g.

```jsx
class MyScreen extends React.Component {
  myMethod = () => {
    // ESLint "syntax error" when it should be valid (see RN docs)
  }

  render() {
    return (
      <View style={Style.container}>
        <Button onPress={this.myMethod}>Do it</Button>
      </View>
    )
  }
}
```

The solution is to simply use `babel-eslint` as the default parser, it's the one used by RN and Prettier anyway, and it's more modern:

- `yarn add babel-eslint eslint-plugin-babel`
- edit `.eslintrc`:
   - add `"parser": "babel-eslint",`
   - add `"babel"` at the begining of the `plugins` array

**Comment by JeremyDolle** [comment]
Hi @antoinerousseau,

A [Pull request](https://github.com/thecodingmachine/react-native-boilerplate/pull/105) is now open with hook. I think your issue will be no longer a problem 😉

**Comment by AurelGit** [comment]
See https://github.com/thecodingmachine/react-native-boilerplate/pull/105
