### ISSUE TITLE
Architecture suggestions

### ISSUE THREAD

**Issue by antoinerousseau** [thecodingmachine/react-native-boilerplate#67]
- Instead of copying the right `Config/index.[env].js`, you could use the `__DEV__` variable.
- I would rename `App/` into `src/` (`App/App.js` does not sound right to me)
- Why not use built-in `fetch` instead of Axios?
- The path for the source files is too verbose imo, e.g. 
`screens/Splash/SplashScreen.js` along with a `SplashScreenStyle.js` could just be `screens/Splash/index.js` along with a `style.js`. 
And that would also make the imports lighter: 
`import SplashScreen from 'screens/Splash/SplashScreen'` becomes 
`import SplashScreen from 'screens/Splash'` which is explicit enough.
Same goes for other folders.
- `import PropTypes from 'prop-types'` instead of 
`import { PropTypes } from 'prop-types'`

**Comment by AurelGit** [comment]
New version of the boilerplate takes care of a lot of your suggestions.

Thanks @antoinerousseau !
