### ISSUE TITLE
Unable to load script. Make sure you're either running a Metro server (run 'react-native start') 

### ISSUE THREAD

**Issue by dextermapalya** [thecodingmachine/react-native-boilerplate#71]
**Unable to load script. Make sure you're either running a Metro server**
Unable to load script. Make sure you're either running a Metro server  (run 'react-native start') or that your bundle index.android.bundle is packaged correctly for release.

**Comment by Memogcia** [comment]
Please give more details about your error, this is a generic message.

**Comment by dextermapalya** [comment]
Please see attached images
When I run react-native run-android I get these errors on my phone

![Screenshot_20190903-094659](https://user-images.githubusercontent.com/51318050/64143879-962fa380-ce2f-11e9-9e12-6b43aa904767.jpg)

![Screenshot_20190903-094655](https://user-images.githubusercontent.com/51318050/64143887-9f207500-ce2f-11e9-8e59-34924cbdc6c8.jpg)

![Screenshot_20190903-094429](https://user-images.githubusercontent.com/51318050/64143889-a2b3fc00-ce2f-11e9-83ae-321ab772a261.jpg)

**Comment by Memogcia** [comment]
Are you running the metro server at the same time? with yarn start --reset-cache, if you do y recommend to clean your project with [this Medium post](https://medium.com/@abhisheknalwaya/how-to-clear-react-native-cache-c435c258834e) just follow the yarn steps, also I recommend to do it all with yarn.

**Comment by AurelGit** [comment]
Hey @dextermapalya 

Indeed, if the metro bundler is not running, you can run `yarn start` on a dedicated terminal, then run `react-native run-android` again.

Hope this will help, and thank you @Memogcia
