### ISSUE TITLE
Idea and question add axios interceptors with access to redux store

### ISSUE THREAD

**Issue by heyaj19** [thecodingmachine/react-native-boilerplate#74]
**Is your feature request related to a problem? Please describe.**
It is, I am trying to figure out how to get axios interceptor access to my store. So I dont have to manually send and add the tokens all the time. 

If there is a way you recommened please let me know?

**Comment by AurelGit** [comment]
Hey @heyaj19 !

Very interesting question.

Here how we deal with this problematic (using apisauce, but you can do the same with axios directly).

Create a main ApiService file to connect your API (if you are using multiple APIs, you can create  MyFirstApiSerivce.js, MySecondApiService.js, etc.)
```javascript
// App/Services/ApiService.js

import { create } from 'apisauce'
import { Config } from 'App/Config'

export const ApiService = create({
  baseURL: Config.API_URL,
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  timeout: 30000,
})
```

Then for each resources, create a specific service file using the global one, for example : 
```javascript
// App/Services/Api/BookingService.js

import { ApiService } from 'App/Services/ApiService'

function get() {
  return ApiService.get('/bookings')
}

export const BookingService = {
  get,
}
```

And inside your sagas, you just have to call them like that : 
```javascript
// App/Sagas/BookingSaga.js

import { put, call } from 'redux-saga/effects'
import { BookingService } from 'App/Services/Api/BookingService'

export function* get() {
  const response = yield call(BookingService.get)

  if (response.ok === true) {
     // do something in case of success
  } else {
     // do something in case of error
  }
}
```

Hope this will help !

**Comment by heyaj19** [comment]
@AurelGit the bigger issue I was trying to solve was trying to add my JWT tokens to my request. I solved it by adding HTTP interceptors to the App,js file and using the store from there. 

Ill look into api sauce thank you

**Comment by heyaj19** [comment]
Another request will be for a future release will be to handle errors that need to be show via a modal - a boilerplate for that
