### ISSUE TITLE
Deprecated componentwillreceiveprops warning

### ISSUE THREAD

**Issue by vivekraj** [thecodingmachine/react-native-boilerplate#75]
Is it okay to ignore the warning "componentwillreceiveprops is deprecated and will be removed in the next major version" ?

**Comment by AurelGit** [comment]
Hello @vivekraj !

I think we have to be attentive to warnings. 
I've just upgrade react-navigation to avoid this warning (because it was linked to a thirdparty package).

See you and thanks for your issue !
