### ISSUE TITLE
Add support for typescript 

### ISSUE THREAD

**Issue by virtualit786** [thecodingmachine/react-native-boilerplate#77]
Typescript support should be added.

**Comment by ozanmanav** [comment]
🎉🔥 Hi,  I made a improved fork with TypeScript from "TCM React Native Boilerplate" repository. It can be useful for those who want to work with Typescript. Also i will open the PR to this repository, maybe we can work another branch.

If you see any error or bug, you can let me know. 

https://github.com/ozanmanav/react-native-boilerplate

Cheers !

**Comment by Angelk90** [comment]
Hi @ozanmanav, It is not possible to open issues on your project.

**Comment by ozanmanav** [comment]
> Hi @ozanmanav, It is not possible to open issues on your project.

Hi @Angelk90, sorry activated issues tab now. Thanks

**Comment by crjacinro** [comment]
Any update to officially support this feature in the current repo?

**Comment by AurelGit** [comment]
It's not planned to natively support TS in this boilerplate.

You can take a look at : https://github.com/react-native-community/react-native-template-typescript, a TypeScript template from the `react-native-community`. 

Hope this will help !

**Comment by Angelk90** [comment]
@AurelGit : How come it won't support TS?

**Comment by ozanmanav** [comment]
Hi Everyone, I've updated reforked repository with current version of the original repository. Thanks for the your latest updates @AurelGit !

Cheers
