### ISSUE TITLE
react-native-debugger's redux support should be added

### ISSUE THREAD

**Issue by iamcxa** [thecodingmachine/react-native-boilerplate#78]
![image](https://user-images.githubusercontent.com/1522808/65575525-9d674e80-dfa2-11e9-8024-335aaccff716.png)

to improve development experience and speed up whole process, the redux's debugger should be integrated. which is easy to do by:

```
// Debug tool integration;
  let composeEnhancers = compose;
  if (__DEV__) {
    // Use it if Remote debugging with RNDebugger, otherwise use remote-redux-devtools
    // eslint-disable-next-line no-underscore-dangle
    composeEnhancers = (window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ ||
      require('remote-redux-devtools').composeWithDevTools)({
      name: Platform.OS,
    });
  }

...

  const store = createStore(
    persistedReducer,
    composeEnhancers(applyMiddleware(...middleware)),
  );
```

**Comment by mitroo** [comment]
Also a solution to monitor network requests would be great. Network monitoring from RND is somehow choppy and introduces weird behaviour in the application.

I've heard that [Reactotron](https://github.com/infinitered/reactotron) could be a solution for tracking network requests, but I've never played it to see how it behaves.

**Comment by iamcxa** [comment]
I're implemented the integration of react-native-debugger. for anyone who need:

https://github.com/ublocks/react-native-boilerplate/blob/develop/%40App/Stores/CreateStore.js#L52

**Comment by AurelGit** [comment]
We are now using `Flipper` for the debug :tada:
https://fbflipper.com/
