### ISSUE TITLE
Why not react native navigation 

### ISSUE THREAD

**Issue by MaliahRajan** [thecodingmachine/react-native-boilerplate#87]

**Comment by AurelGit** [comment]
Both React Navigation and Wix React Native Navigation seems to be good packages.

Some pro/cons are available here : https://blog.logrocket.com/react-navigation-vs-react-native-navigation-which-is-right-for-you-3d47c1cd1d63/

In our point of view, React Navigation seems to be the easiest way to start a project, with a lot of helpful functionalities.
