### ISSUE TITLE
Deep linking support

### ISSUE THREAD

**Issue by saurabhd** [thecodingmachine/react-native-boilerplate#90]
**Is your feature request related to a problem? Please describe.**
Providing a way for the deep linking support in the boilerplate code.

**Describe the solution you'd like**
I wanted to implement the deep linking support in the boilerplate. Therefore I made below adjustments in the code we have:

— Provided we have another screen available where we want to implement deep linking support. 
— In the `App/Navigators/AppNavigator.js` file, we would need to define the screen name in the stack navigator. Along with that, we would need to supply `path` attribute to define a unique screen name as per the code segment below:

```
const StackNavigator = createStackNavigator(
    {
      SplashScreen: SplashScreen,
      MainScreen: {
        screen: ExampleScreen,
      },
      ChatScreen: {
        screen: ChatScreen,
        path: 'chat', // this attribute defines deep linking path
      },
  },
  {
    initialRouteName: 'SplashScreen',
    headerMode: 'none',
  }
)
```
— Then we would need to set the `host` in the `App/Containers/Root/RootScreen.js` and the same host needs to be set in the AppNavigator component props as per the code segment below:
```
render() {
    //Deep linking prefix
    const prefix = 'thecodingmachine://';

    return (
      <View style={styles.container}>
        <AppNavigator
          uriPrefix={prefix}
          // Initialize the NavigationService (see https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html)
          ref={(navigatorRef) => {
            NavigationService.setTopLevelNavigator(navigatorRef)
          }}
        />
      </View>
    )
  }
}
```
— As a next step, we would need to set the host and scheme in Android manifest file. And for iOS, we would need to set the same in the `Info` tab in the xcodeproject.

**Describe alternatives you've considered**
— That was the simplest solution I could manage, but happy to explore and adapt the code.
— @AurelGit - happy to prep this solution as PR if you think it will be fruitful. Thanks.

**Comment by AurelGit** [comment]
Hey @saurabhd !

Sounds perfect :) We did it the same way on our projects, and it could be useful to have it in the BR directly.

We will be very happy to have the PR :)

Thanks !

**Comment by saurabhd** [comment]
Hi @AurelGit - with regards to our discussions happened here, I am posting [this](https://github.com/thecodingmachine/react-native-boilerplate/pull/95) PR. Thanks!

**Comment by AurelGit** [comment]
See #112 😃
