### ISSUE TITLE
Getting Started instructions aren't fully accurate

### ISSUE THREAD

**Issue by bryhasagithub** [thecodingmachine/react-native-boilerplate#96]
**Describe the bug**

**To Reproduce**
1. Go to [introducing the react native boilerplate blog writeup](https://thecodingmachine.io/introducing-the-react-native-boilerplate)
2. Scroll down to 'Getting Started' section.
3. The instructions followed verbatim for running the file might have some new users confused because the command should be: 
`**npx** react-native run-ios`
It is just missing the npx portion of the text.

**Expected behavior**
New people learning react-native expect the command to run but can't get it to run by only running: `react-native run-ios` without the `npx` in the beginning.

**Screenshots**
<img width="1257" alt="Screen Shot 2019-12-09 at 2 46 39 PM" src="https://user-images.githubusercontent.com/11837954/70479881-2a468200-1a93-11ea-980d-d2e9e40907e4.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]

**Additional context**
It might be helpful to point out that this is last touched in 2018 and thought it might be helpful to new learners if it could be adjusted for them. The site was easy to find by Googling react-native boilerplate.

**Comment by AurelGit** [comment]
Absolutely right !
This online article is not up-to-date, we will update it with the V2

**Comment by JeremyDolle** [comment]
The article has been updated http://update-blog-rnboilerplate.thecodingmachine.io.test.thecodingmachine.com/introducing-the-react-native-boilerplate , thank you
