### ISSUE TITLE
Weird paths in project.pbxproj file

### ISSUE THREAD

**Issue by izaa** [thecodingmachine/react-native-boilerplate#97]
Hi,

could you explain why there is a reference to neact-native-gesture-handlerios (neat-) instead of react-native-gesture-handlerios and why backslashes at the beginning and later forward slashes  "$(SRCROOT)..\node_modules\neact-native-gesture-handlerios/**",

For example, see the line https://github.com/thecodingmachine/react-native-boilerplate/blob/master/ios/Boilerplate.xcodeproj/project.pbxproj#L722

If this not a bug or something else, feel free to close / remove this report. Thank you!

**Comment by AurelGit** [comment]
Wow.. Really weird.

The v2 will start with a fresh install of RN and dependencies, so i hope it will be fixed with this release !

**Comment by AurelGit** [comment]
No more `neact-native` in the new version 😸  (i think a fix with the new version of all dependencies and the usage of Pod)
