### ISSUE TITLE
Using Redux Toolkit instead of reduxsauce

### ISSUE THREAD

**Issue by mitroo** [thecodingmachine/react-native-boilerplate#99]
[Redux Toolkit](https://redux-toolkit.js.org/) offers an official, opinionated way to write Redux. From my point of view, it looks more cleaner to write Redux in this style instead of using reduxsauce or nothing at all.

What do you think?

**Comment by JeremyDolle** [comment]
Hi @mitroo, we're currently working on it 😉

**Comment by AurelGit** [comment]
Redux Toolkit is now fully used on the new version of the boilerplate 🎉
